### ISSUE TITLE
error: cannot open Packages database in /var/lib/rpm

### ISSUE THREAD

**Issue by SIJAE-WOO** [parklab/xTea#1]
Hi,

I tried using xTea, but I got below error message.

**python2 /home/users/sijaewoo/bin/xTea/gnrt_pipeline_local_v38.py -i /home/users/sijaewoo/sample_id.txt -b /home/users/sijaewoo/bamfile_list.txt -x null -p /home/users/sijaewoo/test_xTea/ -o submit_jobs.sh -l /home/users/sijaewoo/bin/xTea/rep_lib_annotation -r /home/users/sijaewoo/common_files/hg38/hg38.fa -xtea /home/users/sijaewoo/bin/xTea/ -y 15 -m 32 -n 8 

error: cannot open Packages database in /var/lib/rpm
Traceback (most recent call last):
  File "/home/users/sijaewoo/bin/xTea/gnrt_pipeline_local_v38.py", line 916, in <module>
    sf_ref, sf_gene, sf_black_list, sf_folder_xtea, spartition, stime, smemory, ncores, sf_sbatch_sh)
  File "/home/users/sijaewoo/bin/xTea/gnrt_pipeline_local_v38.py", line 605, in gnrt_running_shell
    gnrt_lib_config(l_rep_type, sf_folder_rep, sf_ref, sf_gene, sf_black_list, sf_folder_xtea, sf_sample_folder)
  File "/home/users/sijaewoo/bin/xTea/gnrt_pipeline_local_v38.py", line 481, in gnrt_lib_config
    if sf_folder_xtea[-1] != "/":
TypeError: 'NoneType' object has no attribute '__getitem__'**

If you know how to solve this problem, please tell me know.

Thanks,

Sijae

**Comment by simoncchu** [comment]
Sounds like some system error, not from xTea. Some solution for similar errors: https://ostechnix.com/solve-error-rpmdb-open-failed-error-centos/
