### ISSUE TITLE
x_TEA_main.py: error: no such option: --bamsnap

### ISSUE THREAD

**Issue by sidi-yang** [parklab/xTea#100]
Dear Simon,

I have run xtea using a case-control mode and got an error like this:

`x_TEA_main.py: error: no such option: --bamsnap`
`Usage: x_TEA_main.py [options]`

I saw some other issues with the same error here, and just wondering should I ignore this error? Does this error affect the outputs?

Thank you,
Sidi

**Comment by simoncchu** [comment]
Yes, you can ignore these errors. It doesn't affect the results.

**Comment by shilpasy** [comment]
@simoncchu , sorry to ask you about the same issue. I get the same exact error but I do obtain any results. My vcf files are being generated, but are blank (only header is present in the .vcf file
The following temp files are also empty: candidate_disc_filtered_cns_post_filtering.txt.td.tmp, 
candidate_disc_filtered_cns_post_filtering.txt.orphan.tmp,
candidate_disc_filtered_cns_post_filtering.txt.td_sibling.tmp,
candidate_disc_filtered_cns_post_filtering_somatic.txt.candidate_somatic_td_cluster_from_ctrl.txt.tmp_clip_chk.txt
