### ISSUE TITLE
Possible to merge TE sites and do genotyping in each sample?

### ISSUE THREAD

**Issue by dr-ashu-geno** [parklab/xTea#104]
Hi. 

Thank you for developing xTea.

A short question: any programs you recommend for merging TE sites in all samples and genotype the sites in each sample after merging step? 
In addition, I have SV data from other programs like Manta, DELLY, etc., do you know how I can merge xTea output with outputs from those programs? (and a program to genotype each sample for list of SVs after merge?).

Thank you in advance,

**Comment by simoncchu** [comment]
I have this script to merge vcfs to one: https://github.com/parklab/xTea/blob/master/xtea/x_vcf_merger.py, but it's not like the standard "genotyping" module, and just merge the vcfs. You can also do this using other tools like bedtoos/vcftools. 

It's not straightforward to merge with Manta/DELLY output, as they also report some TE insertions in their output. I think the easiest way is to write your own scripts.
