### ISSUE TITLE
Alu output didn't go through filter step?

### ISSUE THREAD

**Issue by sidi-yang** [parklab/xTea#105]
Hi Simon,

xTea works well on LINE1 and SVA but I got problem when getting Alu outputs. 

There isn't any "**error**" in the log files, however, there is a line called "**cat: null: No such file or directory**" in the log error file.
And "**Running command with output: cat null /path/to/all_with_polymerphic_flanks.fa.polymerphic_only.fa**" in the output log file.

And this "null" should be a flank.fa file in the directory of "rep_lib_annotation".

- **I saw your markdown saying that sf_flank should be set to null for Alu, so just wondering is this normal to have "cat: null: No such file or directory" in the log file?**

- **I also found the number of Alu events are much more than LINE1 and SVA, which is quite abnormal, and I'm worried that did these Alu events go through filter step?**

And here are all the outout files in an Alu folder (46 files only, less than LINE1 and SVA), and some of them have 0 size:

<img width="652" alt="Screenshot 2024-04-18 at 13 20 40" src="https://github.com/parklab/xTea/assets/99621593/0428c6a0-6521-4835-88b5-627ab8e35ddd">
<img width="650" alt="Screenshot 2024-04-18 at 13 21 10" src="https://github.com/parklab/xTea/assets/99621593/11d23523-099f-45c0-aa99-08a09182aa4a">
<img width="651" alt="Screenshot 2024-04-18 at 13 21 28" src="https://github.com/parklab/xTea/assets/99621593/a3831a3e-23f6-4bff-b529-018da2c9ff40">

**Files with 0 size:**
candidate_disc_filtered_cns_post_filtering.txt.orphan.tmp
candidate_disc_filtered_cns_post_filtering.txt.td.tmp
candidate_disc_filtered_cns_post_filtering.txt.td_sibling.tmp
candidate_disc_filtered_cns_post_filtering_somatic.txt.candidate_somatic_cluster_from_ctrl_td.txt.unique_trsdct_disc_only
candidate_disc_filtered_cns_post_filtering_somatic.txt.candidate_somatic_td_cluster_from_ctrl.txt
candidate_disc_filtered_cns_post_filtering_somatic.txt.candidate_somatic_td_cluster_from_ctrl.txt.tmp_clip_chk.txt
candidate_disc_filtered_cns_post_filtering_somatic.txt.tmp_ctrl_clip_polyA

Could you please help me with this? Is this correct?

**Comment by simoncchu** [comment]
It seems lots of Alu insertions reported from your results (vcf file having ~8000 records?). This is abnormal. We would expect to have around ~1200 germline Alu insertions for each sample. Those "errors" seems ok for me, as we don't expect Alu transductions, thus we didn't check the flanking regions.

**Comment by sidi-yang** [comment]
Sorry for the confusion. 8000 is the size of the file, about 8000 bytes. And about 20 somatic Alu insertion in the output. And thank you very much, I think the outputs are reasonable and correct:)) Thank you again!
