### ISSUE TITLE
xTea output file understanding

### ISSUE THREAD

**Issue by hhysun** [parklab/xTea#107]
I am wonder how to understand the output ALU.vcf file, as it is shown below, the insert Alu sequence was "TSD=+AATGAAAAGGAGAAAGGATGG", but when I searched this seq in the repeat library "hg19_AluJabc_copies_with_flank.fa", I can not find this sequence, does anyone know how to understand the vcf result.   And I also want to know how to classify the vcf output information into Alu families? In my result, all result labeled as "SVTYPE=INS:ME:ALU", but I found in the "nature communication paper", Alu can be classified into AluYa, AluYc blabla...

![Uploading 微信截图_20240524103159.png…]()

**Comment by hhysun** [comment]
![image](https://github.com/parklab/xTea/assets/70497121/cc262707-d6b4-4208-8039-0f76f136ca97)

**Comment by simoncchu** [comment]
These are the target site duplication sequence, not the insertion sequence.

**Comment by hhysun** [comment]
> These are the target site duplication sequence, not the insertion sequence.

Thanks for your reply.
Could you please direct about,  "How can I get the Alu subfamily information based on the output vcf files?"  Many thanks.

**Comment by simoncchu** [comment]
For insertions identified from short reads, xtea does not have subfamily information annotated.

**Comment by hhysun** [comment]
> For insertions identified from short reads, xtea does not have subfamily information annotated.

ok, Isee.  thank you~
