### ISSUE TITLE
About the case-control analysis in Illumina Short-read WGS Data

### ISSUE THREAD

**Issue by recepyilmaz01** [parklab/xTea#108]
Hello,
Thanks for developing xTEA.

As a junior researcher aiming to improve my skills in the field of bioinformatics, I have encountered an issue while utilizing xTEA's case-control mode to identify possible somatic transposon insertions. When I checked the resulting regions in IGV, in several regions, I found the control samples exhibit longer and more clipped reads compared to the case samples. What could be the reason for this? As an example, I am dropping screenshots from the IGVs. 

Would you kindly help me to find a potential solution to my problem?

Many thanks for considering my request.
![Control](https://github.com/parklab/xTea/assets/170867170/54e741d7-fa40-4bbb-a294-de3ebaed23ce)
![Case](https://github.com/parklab/xTea/assets/170867170/6401845d-096b-44f4-914c-5b53d805cef9)

**Comment by simoncchu** [comment]
It looks like there are allele dropouts in the case. See the two heterozygous snps on the right of the screenshot.

**Comment by recepyilmaz01** [comment]
Thanks for the reply.

Based on our findings, the allele frequency in the tumor (case) and matched normal (control) samples was determined to be 0.545. How should we interpret an allele frequency of 0.545 in the context of potential allele dropout? Specifically, can we conclude that despite possible allele dropout in the tumor sample, there is an insertion in the region? Or should this insertion in the tumor sample only be considered a sequencing artifact?
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/Recep/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/Recep/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link=blue vlink=blue>


tSVLEN | TSD | TSDLEN | SUBTYPE | STRAND | AF | INS_INV | REF_REP
-- | -- | -- | -- | -- | -- | -- | --




</body>

</html>

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/Recep/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/Recep/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link=blue vlink=blue>


236 | +AAAACCAAGGTCAT | 14 | two_side_tprt_both | + | 0.545454545 | Not-5prime-inversion | not_in_Alu_copy
-- | -- | -- | -- | -- | -- | -- | --




</body>

</html>

**Comment by simoncchu** [comment]
It's a germline insertion. That's why you observed it in both the case and control. I mean in the tumor sample, there is an allele dropout, thus the VAF is lower than in the control.

**Comment by recepyilmaz01** [comment]
Thank you for your time and support.

Would you kindly tell me if this means that the VAF would be >1.0 if there were a somatic insertion in the tumor sample? All of the VAF values I observed for all insertion sites are <1.0. Does that mean there is no somatic insertion in my tumor sample at all?
