### ISSUE TITLE
output understand

### ISSUE THREAD

**Issue by huangyuanf** [parklab/xTea#11]
hello,everyone,after run xTea,I got  a lot of file,what is the meaning of each file?

**Comment by huangyuanf** [comment]
and I want know how to use the merge_vcf.py,could tell me?thanks

**Comment by simoncchu** [comment]
Hi, the vcf file is the final output. Other files are just intermediate files. You can ignore them.

**Comment by huangyuanf** [comment]
![QQ截图20210802152630](https://user-images.githubusercontent.com/82266837/127821002-a60717b0-eeca-4286-a44e-f54ee037352e.png)
sorry, I do not find vcf file ,this is the out. Is there something wrong? And I notice there are lots of .py file in xtea, I am interesting about x_joint_calling.py and x_vcf_merge.py, where could I find the careful usage of them? Thank you very much
![QQ截图20210802153108](https://user-images.githubusercontent.com/82266837/127821697-5648d521-46eb-4e31-97ce-82d709183197.png)

run_xTEA_pipeline.sh is as following:

PREFIX=/lustre/huangyf/HG002/TE.out/mi-xtea-TE/HG002/
############
############
REF=/lustre/huangyf/HG002/genome/ucsc.hg38.fa
XTEA_PATH=/lustre/huangyf/software/xTea/xtea_long/
BAM_LIST=${PREFIX}"bam_list.txt"
TMP=${PREFIX}"tmp/"
REP_LIB=/lustre/huangyf/rep_lib_annotation/
SVA_REF_COPY=null
############
############
python ${XTEA_PATH}"l_main.py" -C -b ${BAM_LIST} -r ${REF} -p ${TMP} -o ${PREFIX}"candidate_list_from_clip.txt"  -n 8 -w 75 
python ${XTEA_PATH}"l_main.py" -A -b ${BAM_LIST} -r ${REF} -p ${TMP} -i ${PREFIX}"candidate_list_from_clip.txt" -o ${PREFIX}"all_ins_seqs.fa" --rep ${REP_LIB} -n 8 
python ${XTEA_PATH}"l_main.py" -N -b ${BAM_LIST} -r ${REF} -p ${TMP}"ghost" -o ${PREFIX}"ghost_reads.fa" --rmsk /lustre/huangyf/rep_lib_annotation/LINE/hg38/hg38_L1_larger_500_with_all_L1HS.out --cns /lustre/huangyf/rep_lib_annotation/consensus/LINE1.fa --min 4000 -n 8
python ${XTEA_PATH}"l_main.py" -Y -i ${PREFIX}"all_ins_seqs.fa" -r ${REF} -p ${TMP}"classification" --rep ${REP_LIB} -y 15 -o ${PREFIX}"classified_results.txt" -n 8
python ${XTEA_PATH}"l_main.py" --clean -b ${BAM_LIST} -r ${REF} -p ${TMP} -i ${PREFIX}"candidate_list_from_clip.txt"  -n 8

**Comment by simoncchu** [comment]
Sorry, I didn't realize you are running the long read module. Here is an explanation of the fields: https://github.com/parklab/xTea_paper/tree/main/run_tools/xTea/HG002 . You can use `classified_results.txt.merged_TE.txt` (replace TE to the exact type) as your final output. But from your output, seems the file size is small. Should something wrong happened.

**Comment by huangyuanf** [comment]
Ok, thank you! I found I have less Alu and LINE-1,but more SVA in classified_results.txt.merged_TE.txt . The total is almost the same. And I want to know about xtea_long classified_results.txt.merged_TE.txt whether about TE of multiple samples when samplie_id_txt including multiple samples and the condition for merging. And  where could I find the careful usage of x_joint_calling.py and x_vcf_merge.py? Thanks very much

**Comment by simoncchu** [comment]
x_joint_calling.py and x_vcf_merge.py these two are for short reads only.

**Comment by huangyuanf** [comment]
OK, Thank you very much!
