### ISSUE TITLE
Will the coverage of BAM files affect the xTea results?

### ISSUE THREAD

**Issue by sidi-yang** [parklab/xTea#110]
Hi Simon,

Just wondering will the coverage of BAM files affect the results?

Thank you!

**Comment by simoncchu** [comment]
It depends on  the depth. In my earlier tests, the performance drops a lot when the depth is lower than 15x. But since most of the available samples having ~30x or higher depth, I didn't spend much time in optimization on low depth samples.

**Comment by sidi-yang** [comment]
Hi Simon,

Thank you for the answer. But what if one sample has a mean coverage of 30X while the other sample has a mean coverage 70X? 

Do you think xTea will output more TEs when detecting samples with 70X coverage, compared with samples with 30X coverage? 

Or will you say if the coverage is over than 30X, there is no need to dwell on the coverage?

Thank you very much!

**Comment by simoncchu** [comment]
It should be fine. The parameters are adjusted by depth automatically.
