### ISSUE TITLE
Input file for pseudogene insertion calling

### ISSUE THREAD

**Issue by selee222** [parklab/xTea#116]
Hi,
Thank you for the great tool. I am using it to call pseudogene insertions in Illumina short read data. It appears that the file "gencode_v28_GRCh38_exon_annotation.out" is required for this process. However, it seems to be missing from the provided rep_lib_annotation file. Could you please check and, if possible, share this file?

Thank you!

Best regards,
Seungeun

**Comment by simoncchu** [comment]
Hi, the pseudogene module is not exported in the current release. We have a in-house version but haven't finished our full test, and we will release in the next round.
