### ISSUE TITLE
Issue with Somatic Insertion Genotyping in Case-Control Mode

### ISSUE THREAD

**Issue by MuratcanMentes** [parklab/xTea#118]
Hello,

First, I want to express my gratitude for developing xTEA.

I am encountering an issue while using xTEA’s case-control mode to identify somatic transposon (specifically Alu) insertions. Based on my understanding from other issues, the genotype should indicate somatic insertion if it is 1/1 or 0/1 in the tumor and 0/0 in the matched control. However, in my case-control analysis, the resulting VCF file has all genotypes labeled as “./.”.

Could you help me understand why this might be happening? Additionally, are there alternative methods to determine somatic insertions in the resulting VCF file?

Many thanks for considering my request.

**Comment by simoncchu** [comment]
Hi, case-ctrl mode is used to identify somatic TE insertions. We don't expect a genotype information for somatic insertions. We classify germline ones to heterozygous or homozygous to indicate they are inherited from one or both of the parents. But somatic insertions formed post-zygotic, thus should be absent from both parents.

**Comment by MuratcanMentes** [comment]
Thank you for your quick response and clarification.

The IGV screenshots of some regions have caused some confusion. Despite xTEA predicting these regions as somatic insertions, I observed clipped reads and discordant reads in the matched control. Could you help me understand the reason for this discrepancy? Did I misunderstand xTEA's results? Does xTEA identify the regions with confirmed insertions or potential somatic insertions?

Thank you for your time and assistance.

![Control_1](https://github.com/parklab/xTea/assets/69894805/2257d844-be26-4841-8e53-e4dadfc7e373)
![Tumor](https://github.com/parklab/xTea/assets/69894805/403a331e-ee18-44a9-99c6-5ac76553916b)
