### ISSUE TITLE
what's the meaning of "REF_REP=Fall_in_Alu_copy_2.5"?

### ISSUE THREAD

**Issue by sidi-yang** [parklab/xTea#119]
Hi Simon,

This "REF_REP" means "Fall in reference repeat copy or not", but what's the meaning of 2.5? Does it represent the source Alu element for this insertion? And if so, how can I find the information of the source element?

Thank you,
Sidi

**Comment by simoncchu** [comment]
That's the repeat divergent rate from repeatmasker annotation. Smaller value indicates the copy is younger and is more similar to other copies.
