### ISSUE TITLE
 Cannot find the target directory: xTea/xtea/genotyping/trained_model_ssc_py2_random_forest_two_category.pkl.

### ISSUE THREAD

**Issue by caroolcardooso-uwa** [parklab/xTea#120]
Hey there! 

I'm trying to run xtea using conda environment, but the job keeps failing after couple of hours with the same error message:

RuntimeError: Cannot find the target directory:  xtea_project/xTea/xtea/genotyping/trained_model_ssc_py2_random_forest_two_category.pkl.
sort: cannot read: xtea_project/path_work_folder/<..>/SVA/candidate_disc_filtered_cns.txt.high_confident.post_filtering_with_gene_gntp.txt: No such file or directory

Running command: sort -k1,1V -k2,2n -o /xtea_project/path_work_folder/<..>/SVA/candidate_disc_filtered_cns.txt.high_confident.post_filtering_with_gene_gntp.txt.sorted /xtea_project/path_work_folder/<..>/SVA/candidate_disc_filtered_cns.txt.high_confident.post_filtering_with_gene_gntp.txt

These are the versions of some of my libraries
python                    3.7.12  
deep-forest               0.1.7 
bwa                       0.7.18    
setuptools                69.0.3  
scikit-learn              1.0.2 
samtools                  1.20  
xtea                      0.1.6 

Any idea of what might be causing this error? 

Thanks!

**Comment by simoncchu** [comment]
Do these solved issues help?
https://github.com/parklab/xTea/issues/83
https://github.com/parklab/xTea/issues/89

**Comment by caroolcardooso-uwa** [comment]
Hey Simon!! Thanks for the fast response!
Yes it does solve this problem using the code from xtea/bin folder! 
But now I'm getting a new one:

Current working folder is: /scratch/xtea_project/path_work_folder/SVA/tmp/transduction/

Ave coverage is 30.624000000000002: automatic parameters (clip, disc, clip-disc) with value (3, 4 ,1)

Mean insert size is: 416.2787172746123

Standard derivation is: 100.03298121161963

/scratch/conda_envs/xtea_env_37/lib/python3.7/site-packages/sklearn/base.py:338: UserWarning: Trying to unpickle estimator LabelEncoder from version 1.0.1 when using version 1.0.2. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/modules/model_persistence.html#security-maintainability-limitations
  UserWarning,
[2024-07-12 06:04:16.525] Start to evalute the model:
[2024-07-12 06:04:16.527] Evaluating cascade layer = 0
Running command: sort -k1,1V -k2,2n -o /scratch/xtea_project/path_work_folder/SVA/candidate_disc_filtered_cns.txt.high_confident.post_filtering_with_gene_gntp.txt.sorted /scratch/xtea_project/path_work_folder/SVA/candidate_disc_filtered_cns.txt.high_confident.post_filtering_with_gene_gntp.txt

Usage: x_TEA_main.py [options]

x_TEA_main.py: error: no such option: --bamsnap
Usage: x_TEA_main.py [options]

x_TEA_main.py: error: no such option: --bamsnap

Have you had this no such option: --bamsnap error before?

Thanks!

**Comment by simoncchu** [comment]
You can ignore this if you already have the vcf file correctly generated.
