### ISSUE TITLE
About "all_ins_seqs.fa" not found

### ISSUE THREAD

**Issue by 120L021101** [parklab/xTea#123]
Hello,
     When I run xTea_long, I found this err "file all_ins_seqs not found", can you tell me in which stage this file was produced? I want to re-run the script from this stage since the whole procedure costs a lot of time.
     BTW, can you tell me what the space means in this err "no space left on device", does it mean the memory or disk?
     Thank you.

**Comment by eesiribloom** [comment]
@120L021101 what was your solution?
