### ISSUE TITLE
Does xtea only detect some subfamilies of TEs in hg38/19?

### ISSUE THREAD

**Issue by sidi-yang** [parklab/xTea#125]
Hi Simon,

I noticed that in the `rep_lib_annotation/Alu/hg19` folder, there are a series of files named as "hg19_AluJabc_copies_with_flank", but when I opened it I found it actually is ALuY subfamily sequences, not AluJ. The same situation is in LINE also. Just wondering why there is a reference like this? What does this .fa file use for?

Thank you

**Comment by simoncchu** [comment]
The different subfamily copies are of high sequence homology, so it will not cause alignment differences, but introduce more copies will affect the running speed, thus I kept the necessary ones.

BTW, I recommend to ask technical issues on github, thus people met the similar issue can refer to the questions, and I am happy to answer them.  But if this is just your personal interests or question, you could send me email instead.
