### ISSUE TITLE
Dockerfile: RUN rm -rf xTea

### ISSUE THREAD

**Issue by minw2828** [parklab/xTea#126]
Hello,

Thank you for developing the tool. 

I am wondering why you need to have the line 55 of code in your [Dockerfile](https://github.com/parklab/xTea/blob/master/Dockerfile).
`55    RUN rm -rf xTea`

I thought to run the following step, one would still need `xTea/bin/xtea` or `xTea/bin/xtea_long`?

` xtea --case_ctrl --tumor -i sample_id.txt -b case_ctrl_bam_list.txt -p ./path_work_folder/ -o submit_jobs.sh -l /home/ec2-user/rep_lib_annotation/ -r /home/ec2-user/reference/genome.fa -g /home/gene_annotation_file.gff3 --xtea /home/ec2-user/xTea/xtea/ -y 7 -f 5907 --slurm -t 0-12:00 -q short -n 8 -m 25`

Many thanks,
Min

**Comment by simoncchu** [comment]
Hi, the docker file is for germline TE insertion identification, not for somatic. You can revise according for a somatic one.

**Comment by minw2828** [comment]
Hello @simoncchu,

Thank you for your quick reply! 

I have some long read data with N/T match. I'd like to do germline and somatic genotyping, and case-control analyses. 
Which branch and workflow should I go with?

Many thanks,
Min

**Comment by simoncchu** [comment]
For long reads, we don't have a case/ctrl mode right now, although you can run separately on the case and ctrl with the long-read branch: https://github.com/parklab/xTea/tree/xTea_long_release_v0.1.0
