### ISSUE TITLE
Can I run xTEA for mice genomes? & how can i do it? 

### ISSUE THREAD

**Issue by sahuno** [parklab/xTea#128]

**Comment by simoncchu** [comment]
The current released repeat library only works for human, not mice genome. To work on mice, you have to build a mice specific library. This thread may help: https://github.com/parklab/xTea/issues/20

**Comment by sahuno** [comment]
Hi, reading the [instructions](https://github.com/parklab/xTea/tree/master/xtea/rep_lib_prep) 
how can i generate `TE-type.consensus.fa` ? 
2. for mouse mm10 would this  [mm10.fa.out.gz](https://www.repeatmasker.org/genomes/mm10/RepeatMasker-rm405-db20140131/mm10.fa.out.gz) be the `TE-type_rmsk.out` ?

**Comment by simoncchu** [comment]
You can check whether you can find the consensus of the specific subfamily (the active L1 in the species you are checking) from RepBase. Or you can generate by yourself. 

For the repeatmasker file, yes that's the file, but you should parse out the active mouse L1 subfamilies, not all the "LINE1"
