### ISSUE TITLE
ImportError: cannot import name 'CascadeForestClassifier' from 'deepforest'

### ISSUE THREAD

**Issue by GianlucaMattei** [parklab/xTea#129]
Hello, 
I have installed xTea using conda, I tried both 1.6.0 and 1.9.0 versions but I get always the same error after running the generated script "run_xTEA_pipeline.sh". deepforest version is 1.3.3

This is the error I get

`
/data2/gmattei/.conda/envs/xtea/lib/python3.7/site-packages/sklearn/externals/joblib/externals/cloudpickle/cloudpickle.py:47: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
/data2/gmattei/.conda/envs/xtea/lib/python3.7/site-packages/sklearn/ensemble/gradient_boosting.py:34: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  from ._gradient_boosting import predict_stages
/data2/gmattei/.conda/envs/xtea/lib/python3.7/site-packages/sklearn/ensemble/gradient_boosting.py:34: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  from ._gradient_boosting import predict_stages
Traceback (most recent call last):
  File "/data1/Tools/src/xTea/xtea/x_TEA_main.py", line 29, in <module>
    from x_genotype_classify import *
  File "/data1/Tools/src/xTea/xtea/x_genotype_classify.py", line 4, in <module>
    from deepforest import CascadeForestClassifier
ImportError: cannot import name 'CascadeForestClassifier' from 'deepforest' (/data2/home/gmattei/.local/lib/python3.7/site-packages/deepforest/__init__.py)
/data2/gmattei/.conda/envs/xtea/lib/python3.7/site-packages/sklearn/externals/joblib/externals/cloudpickle/cloudpickle.py:47: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
/data2/gmattei/.conda/envs/xtea/lib/python3.7/site-packages/sklearn/ensemble/gradient_boosting.py:34: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  from ._gradient_boosting import predict_stages
/data2/gmattei/.conda/envs/xtea/lib/python3.7/site-packages/sklearn/ensemble/gradient_boosting.py:34: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  from ._gradient_boosting import predict_stages
Traceback (most recent call last):
  File "/data1/Tools/src/xTea/xtea/x_TEA_main.py", line 29, in <module>
    from x_genotype_classify import *
  File "/data1/Tools/src/xTea/xtea/x_genotype_classify.py", line 4, in <module>
    from deepforest import CascadeForestClassifier
ImportError: cannot import name 'CascadeForestClassifier' from 'deepforest' (/data2/home/gmattei/.local/lib/python3.7/site-packages/deepforest/__init__.py)
/data2/gmattei/.conda/envs/xtea/lib/python3.7/site-packages/sklearn/externals/joblib/externals/cloudpickle/cloudpickle.py:47: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
/data2/gmattei/.conda/envs/xtea/lib/python3.7/site-packages/sklearn/ensemble/gradient_boosting.py:34: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  from ._gradient_boosting import predict_stages
/data2/gmattei/.conda/envs/xtea/lib/python3.7/site-packages/sklearn/ensemble/gradient_boosting.py:34: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  from ._gradient_boosting import predict_stages
Traceback (most recent call last):
  File "/data1/Tools/src/xTea/xtea/x_TEA_main.py", line 29, in <module>
    from x_genotype_classify import *
  File "/data1/Tools/src/xTea/xtea/x_genotype_classify.py", line 4, in <module>
    from deepforest import CascadeForestClassifier
ImportError: cannot import name 'CascadeForestClassifier' from 'deepforest' (/data2/home/gmattei/.local/lib/python3.7/site-packages/deepforest/__init__.py)
/data2/gmattei/.conda/envs/xtea/lib/python3.7/site-packages/sklearn/externals/joblib/externals/cloudpickle/cloudpickle.py:47: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
/data2/gmattei/.conda/envs/xtea/lib/python3.7/site-packages/sklearn/ensemble/gradient_boosting.py:34: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  from ._gradient_boosting import predict_stages
/data2/gmattei/.conda/envs/xtea/lib/python3.7/site-packages/sklearn/ensemble/gradient_boosting.py:34: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  from ._gradient_boosting import predict_stages
Traceback (most recent call last):
  File "/data1/Tools/src/xTea/xtea/x_TEA_main.py", line 29, in <module>
    from x_genotype_classify import *
  File "/data1/Tools/src/xTea/xtea/x_genotype_classify.py", line 4, in <module>
    from deepforest import CascadeForestClassifier
ImportError: cannot import name 'CascadeForestClassifier' from 'deepforest' (/data2/home/gmattei/.local/lib/python3.7/site-packages/deepforest/__init__.py)
/data2/gmattei/.conda/envs/xtea/lib/python3.7/site-packages/sklearn/externals/joblib/externals/cloudpickle/cloudpickle.py:47: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
/data2/gmattei/.conda/envs/xtea/lib/python3.7/site-packages/sklearn/ensemble/gradient_boosting.py:34: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  from ._gradient_boosting import predict_stages
/data2/gmattei/.conda/envs/xtea/lib/python3.7/site-packages/sklearn/ensemble/gradient_boosting.py:34: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  from ._gradient_boosting import predict_stages
Traceback (most recent call last):
  File "/data1/Tools/src/xTea/xtea/x_TEA_main.py", line 29, in <module>
    from x_genotype_classify import *
  File "/data1/Tools/src/xTea/xtea/x_genotype_classify.py", line 4, in <module>
    from deepforest import CascadeForestClassifier
ImportError: cannot import name 'CascadeForestClassifier' from 'deepforest' (/data2/home/gmattei/.local/lib/python3.7/site-packages/deepforest/__init__.py)
/data2/gmattei/.conda/envs/xtea/lib/python3.7/site-packages/sklearn/externals/joblib/externals/cloudpickle/cloudpickle.py:47: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
/data2/gmattei/.conda/envs/xtea/lib/python3.7/site-packages/sklearn/ensemble/gradient_boosting.py:34: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  from ._gradient_boosting import predict_stages
/data2/gmattei/.conda/envs/xtea/lib/python3.7/site-packages/sklearn/ensemble/gradient_boosting.py:34: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  from ._gradient_boosting import predict_stages
Traceback (most recent call last):
  File "/data1/Tools/src/xTea/xtea/x_TEA_main.py", line 29, in <module>
    from x_genotype_classify import *
  File "/data1/Tools/src/xTea/xtea/x_genotype_classify.py", line 4, in <module>
    from deepforest import CascadeForestClassifier
ImportError: cannot import name 'CascadeForestClassifier' from 'deepforest' (/data2/home/gmattei/.local/lib/python3.7/site-packages/deepforest/__init__.py)
/data2/gmattei/.conda/envs/xtea/lib/python3.7/site-packages/sklearn/externals/joblib/externals/cloudpickle/cloudpickle.py:47: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
/data2/gmattei/.conda/envs/xtea/lib/python3.7/site-packages/sklearn/ensemble/gradient_boosting.py:34: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  from ._gradient_boosting import predict_stages
/data2/gmattei/.conda/envs/xtea/lib/python3.7/site-packages/sklearn/ensemble/gradient_boosting.py:34: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  from ._gradient_boosting import predict_stages
Traceback (most recent call last):
  File "/data1/Tools/src/xTea/xtea/x_TEA_main.py", line 29, in <module>
    from x_genotype_classify import *
  File "/data1/Tools/src/xTea/xtea/x_genotype_classify.py", line 4, in <module>
    from deepforest import CascadeForestClassifier
ImportError: cannot import name 'CascadeForestClassifier' from 'deepforest' (/data2/home/gmattei/.local/lib/python3.7/site-packages/deepforest/__init__.py)
/data2/gmattei/.conda/envs/xtea/lib/python3.7/site-packages/sklearn/externals/joblib/externals/cloudpickle/cloudpickle.py:47: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
/data2/gmattei/.conda/envs/xtea/lib/python3.7/site-packages/sklearn/ensemble/gradient_boosting.py:34: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  from ._gradient_boosting import predict_stages
/data2/gmattei/.conda/envs/xtea/lib/python3.7/site-packages/sklearn/ensemble/gradient_boosting.py:34: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  from ._gradient_boosting import predict_stages
Traceback (most recent call last):
  File "/data1/Tools/src/xTea/xtea/x_TEA_main.py", line 29, in <module>
    from x_genotype_classify import *
  File "/data1/Tools/src/xTea/xtea/x_genotype_classify.py", line 4, in <module>
    from deepforest import CascadeForestClassifier
ImportError: cannot import name 'CascadeForestClassifier' from 'deepforest' (/data2/home/gmattei/.local/lib/python3.7/site-packages/deepforest/__init__.py)
/data2/gmattei/.conda/envs/xtea/lib/python3.7/site-packages/sklearn/externals/joblib/externals/cloudpickle/cloudpickle.py:47: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
/data2/gmattei/.conda/envs/xtea/lib/python3.7/site-packages/sklearn/ensemble/gradient_boosting.py:34: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  from ._gradient_boosting import predict_stages
/data2/gmattei/.conda/envs/xtea/lib/python3.7/site-packages/sklearn/ensemble/gradient_boosting.py:34: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  from ._gradient_boosting import predict_stages
Traceback (most recent call last):
  File "/data1/Tools/src/xTea/xtea/x_TEA_main.py", line 29, in <module>
    from x_genotype_classify import *
  File "/data1/Tools/src/xTea/xtea/x_genotype_classify.py", line 4, in <module>
    from deepforest import CascadeForestClassifier
ImportError: cannot import name 'CascadeForestClassifier' from 'deepforest' (/data2/home/gmattei/.local/lib/python3.7/site-packages/deepforest/__init__.py)
/data2/gmattei/.conda/envs/xtea/lib/python3.7/site-packages/sklearn/externals/joblib/externals/cloudpickle/cloudpickle.py:47: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
/data2/gmattei/.conda/envs/xtea/lib/python3.7/site-packages/sklearn/ensemble/gradient_boosting.py:34: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  from ._gradient_boosting import predict_stages
/data2/gmattei/.conda/envs/xtea/lib/python3.7/site-packages/sklearn/ensemble/gradient_boosting.py:34: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  from ._gradient_boosting import predict_stages
Traceback (most recent call last):
  File "/data1/Tools/src/xTea/xtea/x_TEA_main.py", line 29, in <module>
    from x_genotype_classify import *
  File "/data1/Tools/src/xTea/xtea/x_genotype_classify.py", line 4, in <module>
    from deepforest import CascadeForestClassifier
ImportError: cannot import name 'CascadeForestClassifier' from 'deepforest' (/data2/home/gmattei/.local/lib/python3.7/site-packages/deepforest/__init__.py)
/data2/gmattei/.conda/envs/xtea/lib/python3.7/site-packages/sklearn/externals/joblib/externals/cloudpickle/cloudpickle.py:47: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
/data2/gmattei/.conda/envs/xtea/lib/python3.7/site-packages/sklearn/ensemble/gradient_boosting.py:34: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  from ._gradient_boosting import predict_stages
/data2/gmattei/.conda/envs/xtea/lib/python3.7/site-packages/sklearn/ensemble/gradient_boosting.py:34: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  from ._gradient_boosting import predict_stages
Traceback (most recent call last):
  File "/data1/Tools/src/xTea/xtea/x_TEA_main.py", line 29, in <module>
    from x_genotype_classify import *
  File "/data1/Tools/src/xTea/xtea/x_genotype_classify.py", line 4, in <module>
    from deepforest import CascadeForestClassifier
ImportError: cannot import name 'CascadeForestClassifier' from 'deepforest' (/data2/home/gmattei/.local/lib/python3.7/site-packages/deepforest/__init__.py)
/data2/gmattei/.conda/envs/xtea/lib/python3.7/site-packages/sklearn/externals/joblib/externals/cloudpickle/cloudpickle.py:47: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
/data2/gmattei/.conda/envs/xtea/lib/python3.7/site-packages/sklearn/ensemble/gradient_boosting.py:34: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  from ._gradient_boosting import predict_stages
/data2/gmattei/.conda/envs/xtea/lib/python3.7/site-packages/sklearn/ensemble/gradient_boosting.py:34: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  from ._gradient_boosting import predict_stages
Traceback (most recent call last):
  File "/data1/Tools/src/xTea/xtea/x_TEA_main.py", line 29, in <module>
    from x_genotype_classify import *
  File "/data1/Tools/src/xTea/xtea/x_genotype_classify.py", line 4, in <module>
    from deepforest import CascadeForestClassifier
ImportError: cannot import name 'CascadeForestClassifier' from 'deepforest' (/data2/home/gmattei/.local/lib/python3.7/site-packages/deepforest/__init__.py)
`

**Comment by simoncchu** [comment]
Can you try to install following https://github.com/parklab/xTea/blob/master/Dockerfile and try again?

**Comment by GianlucaMattei** [comment]
it seems to work... I'll keep you update. 
Thanks

**Comment by GianlucaMattei** [comment]
I am getting this error: 

```

Traceback (most recent call last):
  File "/data1/Tools/src/xTea/xtea/x_TEA_main.py", line 932, in <module>
    gc.predict_for_site(sf_model, sf_xTEA, sf_new)
  File "/data1/Tools/src/xTea/xtea/x_genotype_classify.py", line 137, in predict_for_site
    rf_model_df21.load(sf_model)
  File "/data2/home/gmattei/.local/lib/python3.7/site-packages/deepforest/cascade.py", line 1258, in load
    d = _io.model_loadobj(dirname, "param")
  File "/data2/home/gmattei/.local/lib/python3.7/site-packages/deepforest/_io.py", line 300, in model_loadobj
    raise RuntimeError(msg.format(dirname))
RuntimeError: Cannot find the target directory: /data1/Tools/src/xTea/xtea/genotyping/trained_model_ssc_py2_random_forest_two_category.pkl.
Running command: sort -k1,1V -k2,2n -o /data2/gmattei/Santini/MDS/WGS/Analysis/xTea/Results/MDS1/L1/candidate_disc_filtered_cns.txt.high_confident.post_filtering_with_gene_gntp.txt.sorted /data2/gmattei/Santini/MDS/WGS/Analysis/xTea/Results/MDS1/L1/candidate_disc_filtered_cns.txt.high_confident.post_filtering_with_gene_gntp.txt

sort: cannot read: /data2/gmattei/Santini/MDS/WGS/Analysis/xTea/Results/MDS1/L1/candidate_disc_filtered_cns.txt.high_confident.post_filtering_with_gene_gntp.txt: No such file or directory
Traceback (most recent call last):
  File "/data1/Tools/src/xTea/xtea/x_TEA_main.py", line 964, in <module>
    gvcf.cvt_raw_rslt_to_gvcf(s_sample_id, sf_bam, sf_raw_rslt, i_rep_type, sf_ref, sf_vcf)
  File "/data1/Tools/src/xTea/xtea/x_gvcf.py", line 199, in cvt_raw_rslt_to_gvcf
    with open(sf_raw_rslt_sorted) as fin_rslt:
FileNotFoundError: [Errno 2] No such file or directory: '/data2/gmattei/Santini/MDS/WGS/Analysis/xTea/Results/MDS1/L1/candidate_disc_filtered_cns.txt.high_confident.post_filtering_with_gene_gntp.txt.sorted'

```

anyway this exists

```

(xtea) gmattei@hal:/data1/Tools/src/xTea/xtea/rep_lib_prep$ ll /data1/Tools/src/xTea/xtea/genotyping/trained_model_ssc_py2_random_forest_two_category.pkl
-rw-r--r--. 1 gmattei root 31634410 Oct 25 13:00 /data1/Tools/src/xTea/xtea/genotyping/trained_model_ssc_py2_random_forest_two_category.pkl

```


and the directory exists

```
(xtea) gmattei@hal:/data1/Tools/src/xTea/xtea/rep_lib_prep$ ll /data2/gmattei/Santini/MDS/WGS/Analysis/xTea/Results/MDS1/L1/
total 70928

```

**Comment by simoncchu** [comment]
What's your running commands

**Comment by simoncchu** [comment]
You activate your conda environment (suppose this is how you install following the docker file), then git cloned xtea (git clone https://github.com/parklab/xTea) to a folder say: `/n/path/xTea`. Then, you run with the local downloaded version with  command like `python /n/path/xTea/x_TEA_main.py -i /data2/gmattei/Santini/MDS/WGS/Analysis/xTea/Data/sample_id.txt -b /data2/gmattei/Santini/MDS/WGS/Analysis/xTea/Data/illumina_bam_list.txt -m 120 -x null -p /data2/gmattei/Santini/
MDS/WGS/Analysis/xTea/Results/ -o /data2/gmattei/Santini/MDS/WGS/Scripts/xTea_pipeline.sh -l /data1/Tools/src/xTea/xtea/rep_lib_prep -r /data2/utility/references/genomics/Homo_sapiens_assembly38.fasta -g /data2/utility/Annotation
s/GFF/gencode.v33.chr_patch_hapl_scaff.annotation.gff3 --xtea /n/path/xTea/ -f 5907 -y 7 -t 0-12:00 -q short -n 40` (instead of `./xtea`). Resetting xTea means you set the `--xtea` option to the version you just git cloned.

**Comment by GianlucaMattei** [comment]
Hi, 
I cant run the command you wrote me. 
```
python x_TEA_main.py -i /data2/gmattei/Santini/MDS/WGS/Analysis/xTea/Data/sample_id.txt -b /data2/gmattei/Santini/MDS/WGS/Analysis/xTea/Data/illumina_bam_list.txt -m 120 \
-x null -p /data2/gmattei/Santini/MDS/WGS/Analysis/xTea/Results/ -o /data2/gmattei/Santini/MDS/WGS/Scripts/xTea_pipeline.sh -l /data1/Tools/src/xTea/xtea/rep_lib_prep \
-r /data2/utility/references/genomics/Homo_sapiens_assembly38.fasta -g /data2/utility/Annotations/GFF/gencode.v33.chr_patch_hapl_scaff.annotation.gff3 --xtea /data1/Tools/lib/xTea/xtea -f 5907 -y 7 -t 0-12:00 -q short -n 40

Usage: x_TEA_main.py [options]

x_TEA_main.py: error: no such option: -m

```




Instead I run 


```
python x_TEA_main.py -i /data2/gmattei/Santini/MDS/WGS/Analysis/xTea/Data/sample_id.txt -b /data2/gmattei/Santini/MDS/WGS/Analysis/xTea/Data/illumina_bam_list.txt \
-p /data2/gmattei/Santini/MDS/WGS/Analysis/xTea/Results/ -o /data2/gmattei/Santini/MDS/WGS/Scripts/xTea_pipeline.sh \
-r /data2/utility/references/genomics/Homo_sapiens_assembly38.fasta -n 40
```

Then, as I always did, I run the first script in the generated pipeline

```
sh /data2/gmattei/Santini/MDS/WGS/Analysis/xTea/Results/MDS1/L1/run_xTEA_pipeline.sh
```

I'll keep you update

**Comment by GianlucaMattei** [comment]
Hi, 
I cant run the command you wrote me. 
```
python x_TEA_main.py -i /data2/gmattei/Santini/MDS/WGS/Analysis/xTea/Data/sample_id.txt -b /data2/gmattei/Santini/MDS/WGS/Analysis/xTea/Data/illumina_bam_list.txt -m 120 \
-x null -p /data2/gmattei/Santini/MDS/WGS/Analysis/xTea/Results/ -o /data2/gmattei/Santini/MDS/WGS/Scripts/xTea_pipeline.sh -l /data1/Tools/src/xTea/xtea/rep_lib_prep \
-r /data2/utility/references/genomics/Homo_sapiens_assembly38.fasta -g /data2/utility/Annotations/GFF/gencode.v33.chr_patch_hapl_scaff.annotation.gff3 --xtea /data1/Tools/lib/xTea/xtea -f 5907 -y 7 -t 0-12:00 -q short -n 40

Usage: x_TEA_main.py [options]

x_TEA_main.py: error: no such option: -m

```




Instead I run 


```
python x_TEA_main.py -i /data2/gmattei/Santini/MDS/WGS/Analysis/xTea/Data/sample_id.txt -b /data2/gmattei/Santini/MDS/WGS/Analysis/xTea/Data/illumina_bam_list.txt \
-p /data2/gmattei/Santini/MDS/WGS/Analysis/xTea/Results/ -o /data2/gmattei/Santini/MDS/WGS/Scripts/xTea_pipeline.sh \
-r /data2/utility/references/genomics/Homo_sapiens_assembly38.fasta -n 40
```

Then, as I always did, I run the first script in the generated pipeline

```
sh /data2/gmattei/Santini/MDS/WGS/Analysis/xTea/Results/MDS1/L1/run_xTEA_pipeline.sh
```

I'll keep you update


EDIT:

I've got this error:

```
/data2/gmattei/.conda/envs/xtea/lib/python3.7/site-packages/sklearn/base.py:338: UserWarning: Trying to unpickle estimator LabelEncoder from version 1.0.1 when using version 1.0.2. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/modules/model_persistence.html#security-maintainability-limitations
  UserWarning,
[2024-10-31 09:12:51.597] Start to evalute the model:
[2024-10-31 09:12:51.597] Evaluating cascade layer = 0 
Running command: sort -k1,1V -k2,2n -o /data2/gmattei/Santini/MDS/WGS/Analysis/xTea/Results/MDS1/L1/candidate_disc_filtered_cns.txt.high_confident.post_filtering_with_gene_gntp.txt.sorted /data2/gmattei/Santini/MDS/WGS/Analysis/xTea/Results/MDS1/L1/candidate_disc_filtered_cns.txt.high_confident.post_filtering_with_gene_gntp.txt

Usage: x_TEA_main.py [options]

x_TEA_main.py: error: no such option: --bamsnap
Usage: x_TEA_main.py [options]

x_TEA_main.py: error: no such option: --bamsnap
```

**Comment by simoncchu** [comment]
This one is fine. You can ignore. Have you gotten the vcf file?

**Comment by GianlucaMattei** [comment]
yes!
great, thanks

**Comment by GianlucaMattei** [comment]
yes!
great, thanks
