### ISSUE TITLE
 MELT in your article

### ISSUE THREAD

**Issue by xuxif** [parklab/xTea#14]
Hi,
Could you send me vcf file of MELT from HG002. I have run melt in HG002 but I got far fewer insertion than what your paper show. I run melt-single with default parameter. That will be nice if you could tell me how you run melt.
Thanks!
xuxf

**Comment by simoncchu** [comment]
Hi, the reports here are for technical issues of the method. Please send us email if you want to request other files or if you have other unrelated questions.
