### ISSUE TITLE
[Dockerfile]installing error:chmod: cannot access '*.pyc': No such file or directory The command '/bin/sh -c chmod +x *.pyc' returned a non-zero code: 1

### ISSUE THREAD

**Issue by wangnan9394** [parklab/xTea#15]
Hi,
    Very nice tools! I tried to install on my system using Dockerfile. But the process was stopped. And the terminal showed 
```
Step 14/17 : ENV LANG=C.UTF-8
 ---> Using cache
 ---> 2472a041ff3d
Step 15/17 : COPY *.pyc *.sh ./
 ---> Using cache
 ---> 57417a2fde8f
Step 16/17 : RUN chmod +x *.pyc
 ---> Running in 168d71410252
**chmod: cannot access '*.pyc': No such file or directory
The command '/bin/sh -c chmod +x *.pyc' returned a non-zero code: 1**
```
I tried to fixed it but I did not find whereis the problem. Could you give me a hand?

Bests,
Nan

**Comment by simoncchu** [comment]
Hi Nan, have you tried the conda version? The docker version is an old version that we used to run on a large cohort (https://www.biorxiv.org/content/10.1101/2021.01.29.428895v1.abstract). It is hosted on the docker hub. If you really need to run the docker version, you can follow the cwl here: https://github.com/parklab/xTea/blob/release_xTea_cloud_1.0.0-beta/xtea_hg19.cwl. I would suggest try the latest version on the master branch.

**Comment by wangnan9394** [comment]
Dear Chu,
    Thank you!
    I have tried the conda version on a Amazon ubuntu system. But I faild in the installing process "conda install numpy scikit-learn=0.18.1 pandas -y" because the terminal was not work when i set this command. I started to create a docker envioment for solving the probelm, however, it occured again. Did you met the same situation like me ?

Nan

**Comment by wangnan9394** [comment]
Dear，
I found the matter was the limitation of memory in my sytem, and the guidance was great!
I will close this Q&A.
Thank you！
Nan
