### ISSUE TITLE
How to create hg38_FL_L1_flanks_3k files

### ISSUE THREAD

**Issue by Nurpe** [parklab/xTea#17]
Hi, 
I’m interested in replicate the files created with hg38.
How do you generate files like hg38_FL_L1_flanks_3k.fa? 

Thank you.

**Comment by simoncchu** [comment]
Hi, `hg38_FL_L1_flanks_3k.fa` is generated based on the RepeatMasker annotation. First select the full length L1s, and then for each full length L1, collect the left and right flanking region (extend to 3k). Then put together all the flanks in a fasta file.
