### ISSUE TITLE
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType

### ISSUE THREAD

**Issue by yanmeidoulab** [parklab/xTea#18]
Hi,
Thanks for making this wonderful tool!
I am running version 0.1.6 installed using conda.
we run the case-ctrl model using the following comand:
xtea --case_control --tumor -i sample_id/sample_id.txt -b bam_config/case_ctrl_bam_list.txt -p working/ -o submit_jobs.sh -l rep_lib_annotation/ -r reference/Homo_sapiens_assembly38.fasta -g gff3/gencode.v33.annotation.gff3 --xtea tools/xTea/xtea -y 7 -f 10 --slurm -t 0-12:00 -q indel-debug -n 4 -m 2
but we got the error bellow:
Traceback (most recent call last):
  File tools/miniconda3/envs/mutpipe/bin/xtea", line 1114, in <module>
    if os.path.isfile(sf_bams_10X) == False:
  File "tools/miniconda3/envs/mutpipe/lib/python3.6/genericpath.py", line 30, in isfile
    st = os.stat(path)
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType
The case_ctrl_bam_list.txt file is sth like this:
sample_166 tumor/Panel19-LZ-166T/tumor_deduped.sorted.bam normal/Panel152-LZ-166B/tumor_deduped.sorted.bam

Can you help me out?
Thanks
Ada

**Comment by simoncchu** [comment]
Hi，could you provide full path and try again? For example, change `tumor/Panel19-LZ-166T/tumor_deduped.sorted.bam normal/Panel152-LZ-166B/tumor_deduped.sorted.bam` to its full path.

**Comment by yanmeidoulab** [comment]
Hi chu,
I forgot to set -x null in the command and the problem is solved. 
I will close this Q&A.
Thank you！
