### ISSUE TITLE
annotaion file

### ISSUE THREAD

**Issue by yangyangclover** [parklab/xTea#2]
Dear author,

I am trying to run xTEA locally, there is an error showing 
`IOError: [Errno 2] No such file or directory: '/scratch/yangyang0110/xTea/rep_lib_annotation/LINE/hg19/hg19_L1.fa.out'`

I can't find the `hg19_L1.fa.out` in the annotation folder neither, may I ask if the annotation folder is missing some necessary files?

Looking forward to your reply. Thank you for sharing.

Yang

**Comment by simoncchu** [comment]
Hi, are you using the docker version?

**Comment by yangyangclover** [comment]
> Hi, are you using the docker version?

No, I am using the local version.

**Comment by simoncchu** [comment]
You are right, the file is failed to be included when I generate the compressed file. I have updated the library, please update.
