### ISSUE TITLE
FileNotFoundError

### ISSUE THREAD

**Issue by xuxif** [parklab/xTea#24]
Traceback (most recent call last):
  File "/root/xTea/xtea/x_TEA_main.py", line 1031, in <module>
    pkl_model = gc.load_model_from_file(sf_model)
  File "/root/xTea/xtea/x_genotype_classify.py", line 182, in load_model_from_file
    pickle_model = pickle.load(file, encoding='latin1')
ModuleNotFoundError: No module named 'sklearn.ensemble.forest'
Running command: sort -k1,1V -k2,2n -o ./xtea/HG002/Alu/candidate_disc_filtered_cns.txt.high_confident.post_filtering_with_gene_gntp.txt.sorted ./xtea/HG002/Alu/candidate_disc_filtered_cns.txt.high_confident.post_filtering_with_gene_gntp.txt

sort: cannot read: ./xtea/HG002/Alu/candidate_disc_filtered_cns.txt.high_confident.post_filtering_with_gene_gntp.txt: No such file or directory
Traceback (most recent call last):
  File "/root/xTea/xtea/x_TEA_main.py", line 1065, in <module>
    gvcf.cvt_raw_rslt_to_gvcf(s_sample_id, sf_bam, sf_raw_rslt, i_rep_type, sf_ref, sf_vcf)
  File "/root/xTea/xtea/x_gvcf.py", line 199, in cvt_raw_rslt_to_gvcf
    with open(sf_raw_rslt_sorted) as fin_rslt:
FileNotFoundError: [Errno 2] No such file or directory: './xtea/HG002/Alu/candidate_disc_filtered_cns.txt.high_confident.post_filtering_with_gene_gntp.txt.sorted

I tried to reinstall xtea or install free  same result were return.  Python is 2.7.1 and 'from sklearn.ensemble import RandomForestClassifier' do not show any error or warnings!

**Comment by simoncchu** [comment]
Could you have a try with python3.7?

**Comment by xuxif** [comment]
Yes, I tried with python 3.7. But too much warnings  let me give up!

**Comment by simoncchu** [comment]
Not sure what you mean by warnings. But I cannot repeat your errors. Anyway, depends on you.

**Comment by xuxif** [comment]
Could you please send me the result of HG002 with xTea illumina! Following are warning with python 3.7:
/root/anaconda3/envs/your_env/lib/python3.7/site-packages/sklearn/linear_model/least_angle.py:30: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  method='lar', copy_X=True, eps=np.finfo(np.float).eps,
/root/anaconda3/envs/your_env/lib/python3.7/site-packages/sklearn/linear_model/least_angle.py:167: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  method='lar', copy_X=True, eps=np.finfo(np.float).eps,
/root/anaconda3/envs/your_env/lib/python3.7/site-packages/sklearn/linear_model/least_angle.py:284: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  eps=np.finfo(np.float).eps, copy_Gram=True, verbose=0,
/root/anaconda3/envs/your_env/lib/python3.7/site-packages/sklearn/linear_model/least_angle.py:862: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  eps=np.finfo(np.float).eps, copy_X=True, fit_path=True,
/root/anaconda3/envs/your_env/lib/python3.7/site-packages/sklearn/linear_model/least_angle.py:1101: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  eps=np.finfo(np.float).eps, copy_X=True, fit_path=True,
/root/anaconda3/envs/your_env/lib/python3.7/site-packages/sklearn/linear_model/least_angle.py:1127: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  eps=np.finfo(np.float).eps, positive=False):
/root/anaconda3/envs/your_env/lib/python3.7/site-packages/sklearn/linear_model/least_angle.py:1362: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  max_n_alphas=1000, n_jobs=None, eps=np.finfo(np.float).eps,
/root/anaconda3/envs/your_env/lib/python3.7/site-packages/sklearn/linear_model/least_angle.py:1602: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  max_n_alphas=1000, n_jobs=None, eps=np.finfo(np.float).eps,
/root/anaconda3/envs/your_env/lib/python3.7/site-packages/sklearn/linear_model/least_angle.py:1738: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  eps=np.finfo(np.float).eps, copy_X=True, positive=False):
/root/anaconda3/envs/your_env/lib/python3.7/site-packages/sklearn/decomposition/online_lda.py:29: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  EPS = np.finfo(np.float).eps
/root/anaconda3/envs/your_env/lib/python3.7/site-packages/sklearn/ensemble/gradient_boosting.py:32: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  from ._gradient_boosting import predict_stages
/root/anaconda3/envs/your_env/lib/python3.7/site-packages/sklearn/ensemble/gradient_boosting.py:32: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  from ._gradient_boosting import predict_stages

**Comment by simoncchu** [comment]
Did you get the expected results with the warning?

You can find them here: https://github.com/parklab/xTea_paper

**Comment by xuxif** [comment]
Thank you very much! That is very helpful! But I see two vcf file for alu ( tprt and all) and do not find any descriptions. Could you please send me a short desctiption for each file!

**Comment by simoncchu** [comment]
I am not sure what's the goal here. If you are looking for a benchmark, then use "all". If you want to compare with xTea, then use those in "run_tools/xTea/HG002/".

**Comment by xuxif** [comment]
I'm going to compare genotype between xtea and benchmark of HG002.  I downloaded  HG002_hg38_Illumina_xTea_Alu.txt in ' xTea_paper/run_tools/xTea/HG002/'. When go through that file I only found 23 homo insertion (1/1 or 2).  I don't know if that file should be further processed by other program. Here I focus on next-generateion sequence data from illumina (not long reads or 10X genomic).

**Comment by simoncchu** [comment]
In total? Should be more than that. You could send me email for more discussion on the paper related issues. Here, mainly for the technical issues.
