### ISSUE TITLE
TypeError: 'str' object does not support item assignment

### ISSUE THREAD

**Issue by Jianbiaoli** [parklab/xTea#25]
Hi,

I tried to run xTea on L1, Alu, SVA and HERV respectively.  But I got two types of errors.

For HERV , I got the error below. And the final vcf was not outputted.
Traceback (most recent call last):
  File "/path/xTea/xTea/xtea/x_TEA_main.py", line 1117, in <module>
    xmutation=XMutation(s_working_folder)
  File "/path/xTea/xTea/xtea/x_mutation.py", line 25, in __init__
    self.working_folder[-1] += "/"
TypeError: 'str' object does not support item assignment_

The script is shown below.
PREFIX=/workdir/Sample1/HERV/
ANNOTATION=/path/xTea/rep_lib_annotation/HERV/hg38/hg38_HERV.out
REF=/path/GCA_000001405.15_GRCh38_no_alt_plus_hs38d1_analysis_set.fna
ANNOTATION1=/path/xTea/rep_lib_annotation/HERV/hg38/hg38_HERV.out
GENE=/path/GENCODE/GRCh38_v38/gencode.v38.annotation.gff3
BLACK_LIST=null
L1_COPY_WITH_FLANK=/path/xTea/rep_lib_annotation/HERV/hg38/hg38_HERV_copies_with_flank.fa
SF_FLANK=null
L1_CNS=/path/xTea/rep_lib_annotation/consensus/HERV.fa
XTEA_PATH=/path/xTea/xTea/xtea/
BAM_LIST=${PREFIX}"bam_list.txt"
BAM1=${PREFIX}"10X_phased_possorted_bam.bam"
BARCODE_BAM=${PREFIX}"10X_barcode_indexed.sorted.bam"
TMP=${PREFIX}"tmp/"
TMP_CLIP=${PREFIX}"tmp/clip/"
TMP_CNS=${PREFIX}"tmp/cns/"
TMP_TNSD=${PREFIX}"tmp/transduction/"
/path/Python-3.6.9/bin/python3.6 ${XTEA_PATH}"x_TEA_main.py" -C --dna -i ${BAM_LIST} --lc 3 --rc 3 --cr 1  -r ${L1_COPY_WITH_FLANK}  -a ${ANNOTATION} --cns ${L1_CNS} --ref ${REF} -p ${TMP} -o ${PREFIX}"candidate_list_from_clip.txt"  -n 1 --cp /ldfssz1/ST_MCHRI/CLINIC/USER/lijianbiao/tmp/software_test_20211020/xteagermline/HBN1/pub_clip/
/path/Python-3.6.9/bin/python3.6 ${XTEA_PATH}"x_TEA_main.py"  -D --dna -i ${PREFIX}"candidate_list_from_clip.txt" --nd 5 --ref ${REF} -a ${ANNOTATION} -b ${BAM_LIST} -p ${TMP} -o ${PREFIX}"candidate_list_from_disc.txt" -n 1
/path/Python-3.6.9/bin/python3.6 ${XTEA_PATH}"x_TEA_main.py" -N --dna --cr 3 --nd 5 -b ${BAM_LIST} -p ${TMP_CNS} --fflank ${SF_FLANK} --flklen 3000 -n 1 -i ${PREFIX}"candidate_list_from_disc.txt" -r ${L1_CNS} --ref ${REF} -a ${ANNOTATION} -o ${PREFIX}"candidate_disc_filtered_cns.txt"
/path/Python-3.6.9/bin/python3.6 ${XTEA_PATH}"x_TEA_main.py" -I --dna -p ${TMP} -n 1 -i ${PREFIX}"candidate_disc_filtered_cns.txt" -r ${L1_CNS} --teilen 50 -o ${PREFIX}"internal_snp.vcf.gz"
/path/Python-3.6.9/bin/python3.6 ${XTEA_PATH}"x_TEA_main.py" --gene -a ${GENE} -i ${PREFIX}"candidate_disc_filtered_cns.txt"  -n 1 -o ${PREFIX}"candidate_disc_filtered_cns_with_gene.txt"

The second error appeared in analysis of all four repeat types. 
"Error happen at merge clip and disc feature step: chrEBV not exist" 
"Error happen at merge clip and disc feature step: chrY not exist"
However, the final vcfs of L1, Alu and SVA were successfully generated. Are these vcfs usable?

Thank you,
Jianbiao Li

**Comment by simoncchu** [comment]
The L1, Alu and SVA results should be the final results. They are independent from HERV (and also from each other). 

For HERV, could you post the command you used to generate the scripts? From the posted information, it seems some parameters were not well set.

**Comment by simoncchu** [comment]
This one may help: https://github.com/parklab/xTea/issues/10

**Comment by Jianbiaoli** [comment]
The command is blow. 
/path/xTea/xTea/bin/xtea -i xtea_sampleid -b xtea_bamlist -x null -p ./xtea_germline -o xtea.sub.sh -l /path/xTea/rep_lib_annotation -r /path/GCA_000001405.15_GRCh38_no_alt_plus_hs38d1_analysis_set.fna -g /path/GRCh38_v38/gencode.v38.annotation.gff3 --xtea /path/xTea/xTea/xtea -f 5907 -y 15

#10. Do you mean that I should try to run with "-f 1555" ?

**Comment by simoncchu** [comment]
Yes, can you try that?

**Comment by Jianbiaoli** [comment]
Yeah. I have submit the corrected script. I will let you know when it is finished. 
Thank you!

**Comment by Jianbiaoli** [comment]
Sorry for the reply.
I tried to run xTea with "-f 1555" using germline mode. And I got the final output file named candidate_disc_filtered_cns_with_gene.txt" without error.

But I keep getting another error under case-control mode. The script and error message is shown below.
/path/xTea/xTea/bin/xtea --case_control --tumor -i xtea_sampleidsomatic -b xtea_case_ctrl_bam_list.txt -x null -p xteasomatic -o xtea_somatic_submit_jobs.sh -l /path/xTea/rep_lib_annotation -r /path/GCA_000001405.15_GRCh38_no_alt_plus_hs38d1_analysis_set.fna -g /path/gencode.v38.annotation.gff3 --xtea /path/xTea/xTea/xtea -y 8 -f 1555 -n 8 -m 25

Traceback (most recent call last):
  File "/path/xTea/xTea/xtea/x_TEA_main.py", line 888, in <module>
    n_polyA_cutoff, sf_rep_cns, sf_flank, i_flk_len, bin_size, sf_output, b_tumor)
  File "/path/xTea/xTea/xtea/x_somatic_calling.py", line 93, in call_somatic_TE_insertion
    xclip_disc.sprt_TEI_to_td_orphan_non_td(sf_case_candidates, sf_non_td, sf_td, sf_td_sibling, sf_orphan)
  File "/path/xTea/xTea/xtea/x_clip_disc_filter.py", line 823, in sprt_TEI_to_td_orphan_non_td
    with open(sf_cns) as fin_cns:
FileNotFoundError: [Errno 2] No such file or directory: '/path2/HERV/candidate_disc_filtered_cns_post_filtering.txt'

It is strange that the final output file(candidate_disc_filtered_cns_with_gene.txt) was also generated. The final file is shown blow.
candidate_disc_filtered_cns.txt
candidate_disc_filtered_cns.txt.before_calling_transduction
candidate_disc_filtered_cns.txt.before_calling_transduction.sites_cov
candidate_disc_filtered_cns.txt.before_filtering
candidate_disc_filtered_cns.txt.gntp.features
candidate_disc_filtered_cns.txt.gntp.features0.out
candidate_disc_filtered_cns.txt.high_confident
candidate_disc_filtered_cns_with_gene.txt
candidate_list_from_clip.txt
candidate_list_from_clip.txt_tmp
candidate_list_from_disc.txt
candidate_list_from_disc.txt.clip_sites_raw_disc.txt
tmpclip_peak_candidate.list
tmpclip_reads_tmp0
tmpdiscordant_reads_tmp0
tmpdisc_tmp.list
tmpHBP10.ema.rmdup.realign.bqsr.bam.clipped.sam_sq.txt
tmpHBP10.ema.rmdup.realign.bqsr.bam.clipped.sam.std_out
tmpraw_discordant_reads_tmp0

Could you help me with that?

**Comment by simoncchu** [comment]
I didn't add a somatic module for HERV, as no any somatic HERV has been reported from what I know.

**Comment by Jianbiaoli** [comment]
I get it now. Thank you so much for your help.
