### ISSUE TITLE
how to merge gVCF

### ISSUE THREAD

**Issue by atongsa** [parklab/xTea#26]
how to merge the output gVCF into a single VCF;

does gatk genotype is ok for this procedure.

**Comment by simoncchu** [comment]
I didn't try this before, but I think you can use the gatk toolkits, like the MergeVcfs in Picard, for this, as the outputted vcf followed the standard vcf specification.

**Comment by atongsa** [comment]
then which tools do you used for merging gVCFs, that you have tested and it  works

**Comment by YiweiNiu** [comment]
I also want to know about this. Merging VCFs across samples is always annoying in handing SVs.

**Comment by AhmedArslan** [comment]
This might help:
https://github.com/fritzsedlazeck/SURVIVOR
