### ISSUE TITLE
Running on local machine (without scheduler)

### ISSUE THREAD

**Issue by Mesh89** [parklab/xTea#27]
Hi,

Is there a straightforward way to run your software on a local server where no scheduler is available?

By using your command for illumina data, I get one one script similar to this:
sbatch < /script/for/alu.sh
sbatch < /script/for/line.sh
etc.

I tried manually replacing "sbatch <" with "bash", and it runs for a while, but now it's stuck (hasn't proceeded in a long time and it is using 0 CPU). This is the last output from the software:

[...]
[re-select step]:Filtered out: chrY:16507137 fall in repetitive region.
[re-select step]:Filtered out: chrY:19413366 fall in repetitive region.
[re-select step]:Filtered out: chrY:19678053 fall in repetitive region.
[re-select step]:Filtered out: chrY:20877263 fall in repetitive region.
[re-select step]:Filtered out: chrY:21318615 fall in repetitive region.
[re-select step]:Filtered out: chrY:26345156 fall in repetitive region.
[re-select step]:Filtered out: chrY:26345891 fall in repetitive region.
Running command with output: cat xxx/tools/xTea/LINE/hg38/hg38_FL_L1_flanks_3k.fa xxx/workdirs/xTea/HG00512/HG00512/L1/tmp/transduction/all_with_polymerphic_flanks.fa.polymerphic_only.fa

Running command: bwa index xxx/workdirs/xTea/HG00512/HG00512/L1/tmp/transduction/all_with_polymerphic_flanks.fa

[bwa_index] Pack FASTA... 0.02 sec
[bwa_index] Construct BWT for the packed sequence...
[bwa_index] 0.38 seconds elapse.
[bwa_index] Update BWT... 0.01 sec
[bwa_index] Pack forward-only FASTA... 0.01 sec
[bwa_index] Construct SA from BWT and Occ... 0.21 sec
[main] Version: 0.7.17-r1188
[main] CMD: bwa index xxx/workdirs/xTea/HG00512/HG00512/L1/tmp/transduction/all_with_polymerphic_flanks.fa
[main] Real time: 0.644 sec; CPU: 0.641 sec

How to proceed?
Thanks!

**Comment by simoncchu** [comment]
What you did is the right way. You can remove the `--slurm` parameter when generate the scripts, and it will generate the commands without the cluster header. It works well from my test on cloud instances. Make sure you set the proper number of threads.

**Comment by Mesh89** [comment]
I did not use the --slurm parameters.
As I mentioned, the process is stuck. Is there any way to troubleshoot what went wrong?

**Comment by simoncchu** [comment]
Not quite sure what's wrong there. Does rerun the script solve the problem? I didn't meet this kind of issue before. Looks like some process/thread hang.

**Comment by Mesh89** [comment]
I tried rerunning It did not hang this time. However, it failed with this error message:

Traceback (most recent call last):
  File "xxx/tools/xTea/xtea/x_TEA_main.py", line 1118, in <module>
    xmutation.call_mutations_from_reads_algnmt(sf_sites, sf_cns, n_len_cutoff, n_jobs, sf_merged_vcf)
  File "xxx/tools/xTea/xtea/x_mutation.py", line 39, in call_mutations_from_reads_algnmt
    m_sites=xsites.load_in_qualified_sites_from_xTEA_output(i_len_cutoff)
  File "xxx/tools/xTea/xtea/x_sites.py", line 49, in load_in_qualified_sites_from_xTEA_output
    is_lth=int(fields[-1])
ValueError: invalid literal for int() with base 10: '832.0'

**Comment by simoncchu** [comment]
looks like you are running on some unexpected steps. Would you post the initial commands to generate the scripts? Want to check the parameters you set.

**Comment by Mesh89** [comment]
./tools/xTea/bin/xtea -i $PWD/workdirs/xTea/HG00512/sample.txt -b $PWD/workdirs/xTea/HG00512/sample_alns.txt -x null -p $PWD/workdirs/xTea/HG00512/ -l $PWD/tools/xTea/ -r ~/references/1kg-hg38/GRCh38_full_analysis_set_plus_decoy_hla.fa -g $PWD/tools/xTea/gencode.v33.annotation.gff3 --xtea $PWD/tools/xTea/xtea/ -f 5907 -y 15 -o $PWD/workdirs/xTea/HG00512/run.sh

**Comment by simoncchu** [comment]
The command looks right. `-l` option point to the repeat library folder? Not sure what's wrong there. This module `xmutation.call_mutations_from_reads_algnmt(sf_sites, sf_cns, n_len_cutoff, n_jobs, sf_merged_vcf)` shouldn't be triggered at all. Also, could you change the path to full path and try again? Maybe you need to add a `-n` option.

**Comment by Mesh89** [comment]
Yes, that folder there is a rep_lib_annotation.tar.gz file, which I also uncompressed into Alu/LINE/etc. folders.
All of the paths are already absolute. In fact, relative path do not work (I think your software attempt a ln -s at some point which does not work with relative paths).

**Comment by simoncchu** [comment]
The `-r` option is not a full path. But I am not sure what's wrong there. One thing for sure is the generated commands/steps in the `run.sh` is incorrect.

**Comment by simoncchu** [comment]
Could you follow this one https://github.com/parklab/xTea/blob/master/Demo/run_gnrt_pipeline.sh, and try again？ The `-q`, `-m` and `-t` could be removed.

**Comment by Mesh89** [comment]
I tried use the full path instead of ~, but no luck.

When I run run_gnrt_pipeline.sh I get the following output:

mkdir xxx/tools/xTea/Demo/workdir/NA12878/L1
mkdir xxx/tools/xTea/Demo/workdir/NA12878/Alu
mkdir xxx/tools/xTea/Demo/workdir/NA12878/SVA
mkdir xxx/tools/xTea/Demo/workdir/NA12878/L1//tmp
mkdir xxx/tools/xTea/Demo/workdir/NA12878/L1//tmp/clip
mkdir xxx/tools/xTea/Demo/workdir/NA12878/L1//tmp/cns
mkdir xxx/tools/xTea/Demo/workdir/NA12878/L1//tmp/transduction
mkdir xxx/tools/xTea/Demo/workdir/NA12878/L1//tmp/igv
mkdir xxx/tools/xTea/Demo/workdir/NA12878/Alu//tmp
mkdir xxx/tools/xTea/Demo/workdir/NA12878/Alu//tmp/clip
mkdir xxx/tools/xTea/Demo/workdir/NA12878/Alu//tmp/cns
mkdir xxx/tools/xTea/Demo/workdir/NA12878/Alu//tmp/transduction
mkdir xxx/tools/xTea/Demo/workdir/NA12878/Alu//tmp/igv
mkdir xxx/tools/xTea/Demo/workdir/NA12878/SVA//tmp
mkdir xxx/tools/xTea/Demo/workdir/NA12878/SVA//tmp/clip
mkdir xxx/tools/xTea/Demo/workdir/NA12878/SVA//tmp/cns
mkdir xxx/tools/xTea/Demo/workdir/NA12878/SVA//tmp/transduction
mkdir xxx/tools/xTea/Demo/workdir/NA12878/SVA//tmp/igv

However in worker/NA12878/ there is no run.sh. What should I run?

**Comment by simoncchu** [comment]
There should be .sh file specified in your `-o` option: `-o ${OUT_SCRTP}`.

**Comment by Mesh89** [comment]
Sorry for the delay,

The demo works fine, and I get the results.

However, I still get 

Traceback (most recent call last):   
  File "/home/ramesh/surveyor-ins-paper/tools/xTea/xtea/x_TEA_main.py", line 1118, in <module>
    xmutation.call_mutations_from_reads_algnmt(sf_sites, sf_cns, n_len_cutoff, n_jobs, sf_merged_vcf)
  File "/home/ramesh/surveyor-ins-paper/tools/xTea/xtea/x_mutation.py", line 39, in call_mutations_from_reads_algnmt
    m_sites=xsites.load_in_qualified_sites_from_xTEA_output(i_len_cutoff)
  File "/home/ramesh/surveyor-ins-paper/tools/xTea/xtea/x_sites.py", line 49, in load_in_qualified_sites_from_xTEA_output
    is_lth=int(fields[-1])

when running the HG00512 CRAM from the recent 1000g re-sequencing (ftp://ftp.sra.ebi.ac.uk/vol1/run/ERR398/ERR3988780/HG00512.final.cram)

**Comment by simoncchu** [comment]
I am not sure why change a cram file will be different. The generated steps is incorrect. You need to check your parameter settings.
