### ISSUE TITLE
te library format

### ISSUE THREAD

**Issue by atongsa** [parklab/xTea#28]
1) i want runin te for non-human wgs
2) how should i prepare the library for xTea
3) i mean how to prepare the format of library than xTea need, ps, repeatmasker output format -> xTea library format; edta format -> xTea format

**Comment by simoncchu** [comment]
Right now, we don't have a module for non-human species. I'm working on a module for this now. Should be done very soon.

**Comment by simoncchu** [comment]
I put a readme here, could you have a try? https://github.com/parklab/xTea/tree/master/xtea/rep_lib_prep

**Comment by atongsa** [comment]
thanks, i will try
