### ISSUE TITLE
repeat library preparation

### ISSUE THREAD

**Issue by pxxiao-hz** [parklab/xTea#31]
Hello. xTea is a wonderful tool. I also want to use it in plants.
I want to know the version you used in [https://github.com/parklab/xTea/tree/master/xtea/rep_lib_prep](url)? 
I used `xTea v0.1 for short and linked reads on hg38`, but I didn't find `-P` and `-K`.

**Comment by simoncchu** [comment]
Hi, the version on github has these parameters. Could you double check? https://github.com/parklab/xTea/blob/master/xtea/x_TEA_main.py

**Comment by pxxiao-hz** [comment]
> 

Sorry. I just used this command `xtea -h` and didn't find these options.
I would check it carefully.
Thanks for your prompt reply.

**Comment by simoncchu** [comment]
ah, I should have updated the `-h` output. Thanks.

**Comment by pxxiao-hz** [comment]
Hello,
I have recently tried this software on the test file and encountered this problem:
`Traceback (most recent call last):
   File "/tools/xTea/xTea/xtea/x_TEA_main.py", line 1031, in <module>
     pkl_model = gc.load_model_from_file(sf_model)
   File "/tools/xTea/xTea/xtea/x_genotype_classify.py", line 182, in load_model_from_file
     pickle_model = pickle.load(file, encoding='latin1')
ModuleNotFoundError: No module named 'sklearn.ensemble.forest'`

I am also trying to use it on plants, but when making the TE library, I encountered this error:
`[No module named 'numpy.testing.nosetester']`.
So can you list your packages versions? Such as numpy, scipy, etc.
Best wishes!

**Comment by simoncchu** [comment]
Does this help? https://github.com/parklab/xTea/issues/7

**Comment by pxxiao-hz** [comment]
Yes, it works for me. The test file has been run successfully.

I use xTea on plants, I encountered this error:
`[E::main_mem] fail to open file `/tmp/reads_fa/chr1_497741_hap1_slct.fa'.
[M::bwa_idx_load_from_disk] read 0 ALT contigs
[M::bwa_idx_load_from_disk] read 0 ALT contigs
[M::bwa_idx_load_from_disk] read 0 ALT contigs
[M::bwa_idx_load_from_disk] read 0 ALT contigs
[M::bwa_idx_load_from_disk] read 0 ALT contigs ... `
and I got this file `internal_snp.vcf.gz`, but it didn't has any useful information.

I wonder if there is a problem with the bwa index or align.

**Comment by simoncchu** [comment]
Could you post the command you run?

**Comment by pxxiao-hz** [comment]
The command was: 
`python ~/tools/xTea/xTea/xtea/gnrt_pipeline_local_v38.py -i sample_id.txt -b illumina_bam_list.txt -x null -p ./ -o submit_jobs.sh -l /public/home/pxxiao/project/TIPs/3-ganju/04-xTea/01_te_type_out/ -r /public/home/pxxiao/project/data/02-Citrus/01-genome/01-Citrus_sinensis/SWO.v3.0.genome.fa -g /public/home/pxxiao/project/data/02-Citrus/01-genome/01-Citrus_sinensis/SWO.v3.0.gene.model.gff3 --xtea ~/tools/xTea/xTea/xtea/ -f 5907 -y 32 --lsf -q q2680v2 -n 8`

And the list of outfiles was:
![image](https://user-images.githubusercontent.com/76642822/155838597-0dde0d05-a541-439b-a39e-e14451e43953.png)

The error file was:
[SRR5801703_49176689.txt](https://github.com/parklab/xTea/files/8146342/SRR5801703_49176689.txt)

**Comment by simoncchu** [comment]
Could you try to set a `-m` option, like `-m 16`, and also for `-p` set the full path?
