### ISSUE TITLE
error: no such option: -P -K

### ISSUE THREAD

**Issue by atongsa** [parklab/xTea#32]
i prepare te ref file from https://github.com/parklab/xTea/tree/master/xtea/rep_lib_prep 

```xtea -P -K -p ./ -r path-of-reference-genome.fa -a path-to-rep-lib-folder/full-length-TE-type_rmsk.out -o path-output-folder/TE_copies_with_flank.fa -e 100 ```

but i get error, there is no such opthin: -K -P

**Comment by simoncchu** [comment]
Could you try with "python your-xtea-folder//x_TEA_main.py -P -K ....".
