### ISSUE TITLE
ModuleNotFoundError: No module named 'pysam'

### ISSUE THREAD

**Issue by BenjaminSSimpson** [parklab/xTea#33]
Hi,

Installed XTea using bioconda (Anaconda3/5.3.0) on a linux system to run on an lsf cluster. I am getting a module not found error when submitting the submit_jobs.sh script to the cluster. The error suggests there is no module called pysam. I can confirm I have installed pysam as per the instructions using: "conda install pysam -y". This installed pysam version 0.17.0 with samtools, bcftools and htslib version 1.13. I have also checked that pysam exists within the environment, currently installed in "/home/user1/.conda/envs/your_env/lib/python3.7/site-packages (0.17.0).". Any suggestions would be greatly appreciated.

Full error:
Traceback (most recent call last):
File "home/user1/.conda/envs/your_env/lib/x_TEA_main.py" line 114 in
from x_TEI_locator import *
File "home/user1/.conda/envs/your_env/lib/x_TEI_locator" line 7 in
import pysam
ModuleNotFoundError: No module named 'pysam'

Any suggestions would be greatly appreciated!

**Comment by simoncchu** [comment]
hmm, didn't meet this error before. What's the python version?

**Comment by BenjaminSSimpson** [comment]
I am using python3.7. If I run python directly from the virtual environment and run "import pysam" it returns no error, suggesting it has imported. Typing "pysam" gives "module pysam" then the full path to the installed folder.

Really odd one. I have also tried adding "module load anaconda" and"source activate your_env" to the running scripts, but still having the issue. May I ask, what version of python and pysam you originally write the tool? I might downgrade my environment and see if this runs okay?  Any other suggestions are welcome!

**Comment by simoncchu** [comment]
python3.7 should work. Maybe try with python3.8? It's also stable on 3.8.

**Comment by BenjaminSSimpson** [comment]
I have updated to 3.8 but the same error I am afraid.

**Comment by simoncchu** [comment]
Have you solved this problem? It doesn't like a technic issue. I'll close the ticket for now.
