### ISSUE TITLE
xTea repeat library preparation

### ISSUE THREAD

**Issue by 84AP** [parklab/xTea#34]
Hi,
I would like create new repeat library for xTEA using command:
 xtea -P -K -p ./ -r path-of-reference-genome.fa -a path-to-rep-lib-folder/full-length-TE-type_rmsk.out -o path-output-folder/TE_copies_with_flank.fa -e 100 

However, I get:
xtea: error: no such option: -P
xtea: error: no such option: -K

Could you help me?
Thanks

**Comment by simoncchu** [comment]
Does this help? https://github.com/parklab/xTea/issues/32
