### ISSUE TITLE
Difference between classified_results.txt.merged_LINE1.txt and classified_results.txt.LINE1.txt

### ISSUE THREAD

**Issue by YanmingGan** [parklab/xTea#35]
Hi,

Thanks for developing this tool!
I am running the xTea long v0.1.0.
Under the autogenerated directory which contains all the output, there are two classified_results.txt. for each TE/retroelement, and what is the difference between the two output.

**Comment by simoncchu** [comment]
You can use the `classified_results.txt.merged_LINE1.txt` as the final output. It contains the ones within `classified_results.txt.LINE1.txt`, with extra rescued ones included.
