### ISSUE TITLE
insertion sequences

### ISSUE THREAD

**Issue by dr-ashu-geno** [parklab/xTea#36]
Hi. 

Thank you for developing xTea.
I ran xTea on all my samples, successfully. 
Now, I have a question: Seems that xTea does not report the insertions sequences. Right? 
If so, is there any way to extract the sequence of each ME? 

Thank you in advance,
Best,

**Comment by simoncchu** [comment]
The reads are collected for each insertion (if longer than the insert size, then are the two tail-side reads) under `tmp/cns` folder named `temp_disc.sam` and `temp_clip.sam`. You can split out the reads of each insertion and do a local assembly. I'll export an option for this in the next release.

**Comment by dr-ashu-geno** [comment]
Thank you so much for your reply. 

And a short question, have you ever tried merging the ME insertion sites across all the samples, and genotyping each sample for the list of merged sites? If so, what programs do you recommend me use for this?

Thank you in advance,
Best regards,

**Comment by simoncchu** [comment]
We don't have a joint genotyping module right now. Only have the gVCF level genotype. When I tried to merge them with some in-house script, if an insertion is not in a samples, I set the genotype as "0/0". I was told some tool like survivor could do the vcf merging, although I didn't try before.
