### ISSUE TITLE
Broken relative symbolic link

### ISSUE THREAD

**Issue by ramonamerong** [parklab/xTea#37]
I have been trying to get xTea running on a HPC, but I am encountering several errors:
First, the program tries to access a file with the clipped reads but cannot find it and therefore creates a symbolic link:
```
[M::bwa_idx_load_from_disk] read 0 ALT contigs
[E::main_mem] fail to open file `output/xtea/PMLBM000AAF_PMCRZ500LPO_WGS.subset.chr1/pub_clip/0/PMLBM000AAF_PMCRZ500LPO_WGS.subset.chr1.bam.clipped.fq'.
Running command: ln -s output/xtea/PMLBM000AAF_PMCRZ500LPO_WGS.subset.chr1/HERV/tmp/clip/0/PMLBM000AAF_PMCRZ500LPO_WGS.subset.chr1.bam.clipped.fq output/xtea/PMLBM000AAF_PMCRZ500LPO_WGS.subset.chr1/pub_clip/0/PMLBM000AAF_PMCRZ500LPO_WGS.subset.chr1.bam.clipped.fq
```
However, as I had provided a relative path to the '-p' option, it also tries to create a symbolic link with relative path, which is sadly broken.
As a result, bwa cannot access the reads via the symbolic link and produces the following error:
`ValueError: file has no sequences defined (mode='r') - is it SAM/BAM format? Consider opening with check_sq=False`.

If you think something else is at play, I would be happy to provide any additional info.

**Comment by simoncchu** [comment]
Could you try with the absolute path? It will always try to create a softlink as several of the modules are shared when you run on different types of TEs, and I put a softlink in a public folder to avoid run the module several times.

**Comment by ramonamerong** [comment]
That solved it!
However xTea seems to freeze somewhere in the middle of the pipeline, produces no error and has an exit code of 0.
The last files that were created are:
```
candidate_disc_filtered_cns.txt.high_confident
candidate_disc_filtered_cns.txt.gntp.features0.out
candidate_disc_filtered_cns.txt.gntp.features
candidate_disc_filtered_cns.txt.before_filtering
candidate_disc_filtered_cns.txt.before_calling_transduction.sites_cov
candidate_disc_filtered_cns.txt.before_calling_transduction
candidate_disc_filtered_cns.txt
```

And the last few lines of the log:
```
Running command: bwa mem -t 2 -T 9 -k 9 -o /hpc/pmc_gen/rvanamerongen/output/xtea/PMLBM000AAF_PMCRZ500LPO_WGS.subset.chr1/HERV/tmp/cns/temp_clip.sam.non_polyA.sam /hpc/pmc_gen/rvanamerongen/software/callers/xtea/rep_lib_annotation/consensus/HERV.fa /hpc/pmc_gen/rvanamerongen/output/xtea/PMLBM000AAF_PMCRZ500LPO_WGS.subset.chr1/HERV/tmp/cns/candidate_sites_all_clip.fq.non_polyA.fq

Running command: bwa mem -t 2 -T 7 -k 7 -o /hpc/pmc_gen/rvanamerongen/output/xtea/PMLBM000AAF_PMCRZ500LPO_WGS.subset.chr1/HERV/tmp/cns/temp_clip.sam.polyA.sam -c 70 /hpc/pmc_gen/rvanamerongen/software/callers/xtea/rep_lib_annotation/consensus/HERV.fa /hpc/pmc_gen/rvanamerongen/output/xtea/PMLBM000AAF_PMCRZ500LPO_WGS.subset.chr1/HERV/tmp/cns/candidate_sites_all_clip.fq.polyA.fq

Running command: bwa mem -t 2 -o /hpc/pmc_gen/rvanamerongen/output/xtea/PMLBM000AAF_PMCRZ500LPO_WGS.subset.chr1/HERV/tmp/cns/temp_disc.sam /hpc/pmc_gen/rvanamerongen/software/callers/xtea/rep_lib_annotation/consensus/HERV.fa /hpc/pmc_gen/rvanamerongen/output/xtea/PMLBM000AAF_PMCRZ500LPO_WGS.subset.chr1/HERV/tmp/cns/candidate_sites_all_disc.fa
```

**Comment by ramonamerong** [comment]
Hi, my command is:
```
wDir=$(pwd)
xteaPath=software/callers/xtea
outputPath=output/xtea
$xteaPath/bin/xtea -i $wDir/input/sample_id.txt -b $wDir/input/illumina_bam_list.txt -x null -p $wDir/$outputPath -o $wDir/scripts/xtea_test_submit_jobs.sh -l $wDir/$xteaPath/rep_lib_annotation -r $(cat $wDir/input/illumina_bam_list.txt) -g $wDir/$xteaPath/known_genes_hg38.gff3 --xtea $wDir/$xteaPath/xtea -f 1555 -y 15 --slurm -t 0-12:00 -n 2 -m 14
```
When running individual generated scripts instead of using the submit_jobs.sh I am getting errors that some file could not be found, starting with the fourth python command in the generated script:
`FileNotFoundError: [Errno 2] No such file or directory: '/hpc/pmc_gen/rvanamerongen/output/xtea/PMLBM000BBJ_PMCRZ904LTU_WGS.subset.chr1:143200001-248956422/Alu/candidate_disc_filtered_cns2.txt'`

I also notice that none of the earlier three python commands outputs a file named 'candidate_disc_filtered_cns2.txt'.

**Comment by simoncchu** [comment]
I think the `-r` option is wrong. You need to specify the reference genome.
