### ISSUE TITLE
Case-control mode

### ISSUE THREAD

**Issue by maxfieldk** [parklab/xTea#38]
Hi, 
I am trying to run xTea in case-control mode but I get the following error when running the first step:

"Usage: xtea [options]

xtea: error: no such option: --case_ctrl"

Any help would be greatly appreciated.
Thanks!

**Comment by simoncchu** [comment]
Could you have a try with "--case_control"? It's a version discrepancy in readme...

**Comment by maxfieldk** [comment]
Fantastic, that seems to have done the trick, thank you!
And to be sure, do I need to specify a bam file after the --tumor flag? In the read me example nothing follows this flag. If no file is needed, how does the --tumor flag change the case-control mode behavior?
Cheers,
Maxfield

**Comment by simoncchu** [comment]
No, you don't need to set a bam file. The case and ctrl bams are specified in  `-b case_ctrl_bam_list.txt`. Please follow the input section in readme. Here `--tumor` flag is to tell the program to use somatic specific parameters (cutoffs). You need to keep it.

**Comment by maxfieldk** [comment]
I see. In my case I am looking for L1 insertions which occur during cell culture passaging. I have sequencing data on a bulk population of primary cells (my 'control') as well as a single cell from this culture after many passages (my 'case'). The idea is to estimate the rate of L1 insertions per passage in these cells.
Do you think it would be more appropriate to omit the --tumor flag OR to include it and set a very high tumor purity flag like 0.95?
Thank you again for all your help!

**Comment by simoncchu** [comment]
To improve the sensitivity, I would suggest to keep the --tumor option.
