### ISSUE TITLE
Should I use bwa mem -M -Y options?

### ISSUE THREAD

**Issue by MarcelloMalpighi** [parklab/xTea#39]
Hello,
I am working on some human paired-end short-read data and I have two questions about how to prepare proper bam file with bwa and one about how to compare xTea and MELT results.
Firstly, I am using MarkDuplicates(Picard) to remove duplicates and it is recommended to use `bwa mem -M            mark shorter split hits as secondary` for [facilitating the working of MarkDuplicates](https://sites.google.com/a/broadinstitute.org/legacy-gatk-forum-discussions/2019-02-11-2018-08-12/21351-BWA-mem-M-option). I wonder if `-M` will disturb xTea? 
Secondly, xTea realigns clipped and discordant reads to the consensus. Should `bwa mem -Y            use soft clipping for supplementary alignments` be used to make sure xTea extracts sequences required for realignment?
What's more,  I plan to compare xTea and MELT results just as [xTea paper](https://www.nature.com/articles/s41467-021-24041-8) did, but I am confused about the criterion of overlapping TE insertions. Should overlapping TE insertions be defined as insertions whose breakpoint are exactly the same in both xTea and MELT results or some kind of difference is allowed? 
Many thanks.

**Comment by simoncchu** [comment]
For your first question, it doesn't matter whether you set `-M` or `-Y` option or not. xTea will re-do the alignment for the clipped reads (primary alignments only). 
For the second question, you need to set some slack value when comparing the breakpoints. Because for one insertion, there are actually two breakpoints (there is a target site duplication between them, usually short). Tools (including xTea) only report one breakpoint, but depends on settings, for one insertion, maybe different breakpoints are reported for the same insertion. Thus, you cannot require exactly the same. And, most of the time, distance between two insertions are much larger than the value you set, thus it will not affect the comparison results much.

**Comment by MarcelloMalpighi** [comment]
Thanks a lot ! 
But as for the first question, I got different results when using `bwa -Y`. The codes and results are as follows.
bwa code without -Y
`@PG     ID:bwa  PN:bwa  VN:0.7.17-r1188 CL:bwa mem -M -R @RG\tID:SRR1264615\tLB:SRR1264615\tPL:Illumina\tPU:SRR1264615\tSM:SRR1264615 -t 20...
`
xtea result without -Y
`awk '{print $1}' SRR1264615_sorted_ALU.vcf | uniq -c | tail -23`
`110 chr1
    129 chr2
     83 chr3
     88 chr4
     85 chr5
    110 chr6
     67 chr7
     73 chr8
     62 chr9
     72 chr10
     64 chr11
     79 chr12
     62 chr13
     54 chr14
     41 chr15
     23 chr16
     22 chr17
     38 chr18
     14 chr19
     19 chr20
     12 chr21
      3 chr22
     23 chrX`

bwa code with -Y
`@PG     ID:bwa  PN:bwa  VN:0.7.17-r1188 CL:bwa mem -M -Y -t 20 -R @RG\tID:SRR1264615\tLB:SRR1264615\tPL:Illumina\tPU:SRR1264615\tSM:SRR1264615...
`
xtea result with -Y
`awk '{print $1}' test_Y_SRR1264615_sorted_ALU.vcf | uniq -c | tail -23`
` 108 chr1
    126 chr2
     80 chr3
     82 chr4
     82 chr5
    108 chr6
     66 chr7
     72 chr8
     63 chr9
     72 chr10
     63 chr11
     72 chr12
     58 chr13
     52 chr14
     37 chr15
     22 chr16
     21 chr17
     39 chr18
     14 chr19
     18 chr20
     13 chr21
      4 chr22
     21 chrX
`

I also want to extract the clipped and discordant reads from `tmp/cns/temp_clip.sam` and `tmp/cns/temp_disc.sam` just as #36 referred, but I could not fully understand these two files. What is the meaning of numbers between `~`, i.e., `~R~1~`  `~1~0~0~1~1~` in `chr1~890330~R~1~890451~1~0`(from temp_clip.sam) and `SRR1264615.423066703~1~0~0~1~1~31020097~chr12~31020266~0`(from temp_disc.sam)? How can I get the complete sequence of clipped reads? (They are incomplete in `temp_clip.sam` and identifiers are not given)
