### ISSUE TITLE
SVLEN=0 for some TEs

### ISSUE THREAD

**Issue by dr-ashu-geno** [parklab/xTea#41]
Hello. 

I have run xTea on lots of samples (Illumina paired-end reads) successfully. Thank you for developing the program.

I have a question about the length of TEs. For some of them, length is 0. May I ask what it means?
Do I need to filter out TEs like these from the output? 

And a short question: any filtering options after running the program? (besides grep -v "orphan" output.vcf > output_new.vcf)

Thank you in advance,

Best regards,

**Comment by simoncchu** [comment]
>I have a question about the length of TEs. For some of them, length is 0. May I ask what it means?
Do I need to filter out TEs like these from the output?
It means there is an insertion identified, but the size is not (or failed to be) estimated. 

>And a short question: any filtering options after running the program? (besides grep -v "orphan" output.vcf > output_new.vcf)
Depends on your application. For germline calling, that's the final results I'm using.
