### ISSUE TITLE
xtea temp file undersatand

### ISSUE THREAD

**Issue by huangyuanf** [parklab/xTea#42]
hello,how can I got the number of  tranposable element clipped reads and dicount pais reads under the cutoff. Is there some intermediate file you can tell me? Because there's nothing in the temp file about what each column represents ?thanks

**Comment by simoncchu** [comment]
These are saved in the final VCF. You can check from the header to get the related fields.

**Comment by huangyuanf** [comment]
I know final VCF contain such information;but I want to learn record which clip reads and diacount reads under the cutoff ,may I find these records in temp file? thank you

**Comment by simoncchu** [comment]
There are many temporary files. I'm afraid you need to check the code to get what you want...
