### ISSUE TITLE
Does xTea only make "non-reference" calls?

### ISSUE THREAD

**Issue by billytcl** [parklab/xTea#43]
Hi, thanks for writing this interesting pipeline!

Just a quick question -- does xTea only produce non-reference calls, or does it call everything? Does xTea filter these out? I'm asking because I see the reference annotation file (which is a bwa-index fasta file), but I'm unclear on how this is used. What I'd like to do is see if xTea is properly calling some canonical sites that I know should be in my sequenced sample.

Billy

**Comment by simoncchu** [comment]
Yes, it's only for non-reference insertion.

**Comment by billytcl** [comment]
Thanks for writing back quickly! Is there a way I can check on whether it's making any of the reference calls? Perhaps one of the intermediate files? It doesn't even need to be an official "call" itself -- we just want to see if any signals are detected in some control reference regions.

**Comment by simoncchu** [comment]
No, the features are totally different for insertions and reference copies, as reference ones will be shown as "deletion" if the individual does not have the copy. The current version doesn't work for that.
