### ISSUE TITLE
Missing python scripts from the current package

### ISSUE THREAD

**Issue by ss6025** [parklab/xTea#45]
Hi, 
The following py script is missing from the directory xTea/xtea 
Traceback (most recent call last):
  File "/work/greenbaum/users/suns3/xTea/xtea/x_TEA_main.py", line 128, in <module>
    from x_TE_associated_sv import *

After comment out this package in the main py, another py script was found to be missing "x_BamSnap". Could you please upload those functions if they are necessary?  

Thank you so much.

Best,
Siyu

**Comment by simoncchu** [comment]
Sorry it's a version issue. I updated the code. Try again.

**Comment by ss6025** [comment]
Hi Simon,

Thank you so much for the prompt response. I noticed the 0.1.7 version
after sending out the msg. I am about to try it again.

Best,
Siyu

On Wed, May 4, 2022 at 6:37 PM Simon C Chu ***@***.***> wrote:

> Sorry it's a version issue. I updated the code. Try again.
>
> —
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_parklab_xTea_issues_45-23issuecomment-2D1117997396&d=DwMCaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=OEFxsYejLcXXsIYPNDdsGA&m=AJfbeaOVY08Bq0vU4TwudRVRKnu1iD3FI1WrrUaJ487_g82gOeX1cvSHbUauvMQI&s=9EM1vUmd993DQ5U3wtSdqIuXBK1mVvHGiuscHi9RWwU&e=>,
> or unsubscribe
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_ACEMTK4W62E6JUUG62RQKTDVIL33NANCNFSM5VDK4SNQ&d=DwMCaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=OEFxsYejLcXXsIYPNDdsGA&m=AJfbeaOVY08Bq0vU4TwudRVRKnu1iD3FI1WrrUaJ487_g82gOeX1cvSHbUauvMQI&s=xd1GgF0CeYnZ9m0EQRTXQvnEstg_GYkbjdCPLEB8ixA&e=>
> .
> You are receiving this because you modified the open/close state.Message
> ID: ***@***.***>
>


-- 
*Siyu Sun | PhD trained in Gresham Lab
<https://greshamlab.bio.nyu.edu/> (NYU)*
Cell: 917-767-3644
Email: ***@***.***
