### ISSUE TITLE
An Odd Output ""invalid literal for int() with base 10: 'pseudogene' "

### ISSUE THREAD

**Issue by yr542** [parklab/xTea#52]
I ran the run_gnrt_pipleine.sh and then chose to run locally and then I came across some difficulties in using the software. I was wondering if you could help me as I am struggling to run xTea on my machine and I got an odd output "invalid literal for int() with base 10: 'pseudogene' ". Could you help me to figure out why this occurred in this case and how to avoid getting this error?

```

ValueError: invalid literal for int() with base 10: 'pseudogene'
/home/user/anaconda3/lib/python3.9/site-packages/sklearn/base.py:329: UserWarning: Trying to unpickle estimator LabelEncoder from version 1.0.1 when using version 1.0.2. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/modules/model_persistence.html#security-maintainability-limitations
  warnings.warn(

```
Thank you for your time.

**Comment by simoncchu** [comment]
For Alu, are there content within `candidate_disc_filtered_cns2.txt.high_confident` ?

**Comment by yr542** [comment]
How would that be fixed?

**Comment by simoncchu** [comment]
Replied through email. Looks like the annotation file one dosesn't match.
