### ISSUE TITLE
xTea on plants - other repeat type

### ISSUE THREAD

**Issue by DR-genomics** [parklab/xTea#53]
Hello @simoncchu 

I am trying to use xTea on plants. I was having issue with creating repeat lib libraries earlier, however I was able to rectify it and created a repeat lib successfully based on the instructions provided in https://github.com/parklab/xTea/tree/master/xtea/rep_lib_prep

I am interested to do the xTea analysis on gypsy and copia superfamilies. However, I couldn't able to figure out how to specify it for the -y flag. 

Can you please direct me here? 

Thanks

**Comment by simoncchu** [comment]
Please set to 32 and have a try. I had a section for this in readme: https://github.com/parklab/xTea/tree/master/xtea/rep_lib_prep
