### ISSUE TITLE
How to extract clipped/discordant reads

### ISSUE THREAD

**Issue by MarcelloMalpighi** [parklab/xTea#54]
Hello, 
I also want to extract the clipped and discordant reads from `tmp/cns/temp_clip.sam` and `tmp/cns/temp_disc.sam` just as [#36](https://github.com/parklab/xTea/issues/36) referred, but I could not fully understand these two files. What is the meaning of numbers between `~`, for example, `~R~1~ ~1~0~0~1~1~ in chr1~890330~R~1~890451~1~0`(from `temp_clip.sam`) and `SRR1264615.423066703~1~0~0~1~1~31020097~chr12~31020266~0`(from `temp_disc.sam`)? How can I get the complete sequence of clipped reads? They are incomplete in `temp_clip.sam` and identifiers are not given.
Another question is how to set the clipped/discordant reads cutoff to a number which changes with the read depth around the insertion, such as 1/2 depth or 1/3 depth?
Many thanks.

**Comment by simoncchu** [comment]
you can convert the sam to fastq/fasta for the clipped and discordant reads. The "full read" of the clipped ones are not saved, only the clipped part is saved. You need to go to the original bam to extract that. You can set a `--user` option to set customer cutoffs (see the readme page).

**Comment by MarcelloMalpighi** [comment]
Thanks for your reply. 
I am still a little confused about how to get complete clipped reads. As I referred, read identifiers like` SRR1264615.423066703` are shown in `temp_disc.sam` but no identifiers are given in `temp_clip.sam`, so how should I locate clipped reads in the original bam?
As for the second question, actually I wonder whether it is possible to set the cutoff to a variable like` cutoff = 1/2 depth` where  `depth` updates when detecting a new insertion instead of a fixed number, for example, `cutoff  = 1` or `cutoff  = 2`.
Many thanks.

**Comment by simoncchu** [comment]
The clipped read id are not saved, as I only need to know the number of clipped reads, and don't want to know which is clipped. You have to go to the raw bam to get this. 

For the second one, the current setting doesn't support a parameter of `ratio of the depth`. One quick way is you run the first clip step, and it will generate a file contained the depth information, then you set a different job to set your wanted cutoff.

**Comment by MarcelloMalpighi** [comment]
Got it, thanks.
