### ISSUE TITLE
no vcf

### ISSUE THREAD

**Issue by ZunpengLiu** [parklab/xTea#55]
Hello Sir,

thank you very much for this cool tool!!

when I run this pipeline for Illumina short reads, I only got the files like that, and there is no vcf file. Do you know the reason for that?

<img width="1107" alt="image" src="https://user-images.githubusercontent.com/31592626/185650773-3b6b4892-dcf1-40c2-b2fc-e20376e73ca5.png">

<img width="723" alt="image" src="https://user-images.githubusercontent.com/31592626/185650857-58c4428d-ca25-4c57-b101-77e17c290fcd.png">

Many thanks!

Best,

Zunpeng

**Comment by simoncchu** [comment]
I think it doesn't reach the end. Probably some error happens in the middle step. You need to check the log.

**Comment by ZunpengLiu** [comment]
Yes, thank you!

For the log file, I got as follows,

<img width="1703" alt="image" src="https://user-images.githubusercontent.com/31592626/185796700-cbc5b6a6-5f06-4337-b87f-6a47879583e3.png">
Do you have any idea about this?


Thanks!

Best,

Zunpeng

**Comment by simoncchu** [comment]
Oh, you are working on HERV? Then, 
<img width="406" alt="image" src="https://user-images.githubusercontent.com/3340363/185801075-8b22b927-ef23-46ce-8391-801f9f0d3894.png">
this is the output.
