### ISSUE TITLE
Still unable to run in Mac

### ISSUE THREAD

**Issue by proukakis** [parklab/xTea#57]
Hello, i really wanted to try again, but it seems that the requirement for wtdbg2 makes it impossible.

conda create -n your_env xtea=0.1.6

Collecting package metadata (current_repodata.json): done
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: - 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed

PackagesNotFoundError: The following packages are not available from current channels:

  - wtdbg

And it seems that wtdbg can not be installed on mac

any suggestion?

thanks
christos

**Comment by simoncchu** [comment]
sorry for the late reply. I don't think xTea could run smoothly on mac. Not the installation, but there are some errors reported before by other users when run on some step. I would suggest to try on on linux server.

**Comment by proukakis** [comment]
ok thanks

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
