### ISSUE TITLE
Runing the tool in Terra Cloud

### ISSUE THREAD

**Issue by ohan-Bioinfo** [parklab/xTea#58]
Dear Developer 
Thank you for the great tools

Currently, I have no issue working locally, but kindly im facing some challenges implementing it in the cloud, and terra cloud broad or docker store the tools xTea not available, so I had to create a WDL from a scratch, probably others can use it in the future, but keep failing probably I'm missing something.

Would you please check the wdl script below:

```
task XTes {
    String sample
    File input_bam
    File genome_tar
    File repeats_tar
    File gencode
    Int nthreads
    Int f
    Int y

    command {
        python /usr/local/bin/gnrt_pipeline_germline_cloud_v38.py -D -o run_jobs.sh --xtea /usr/local/bin/ -p . \
        -i ${sample} \
        -b ${input_bam} \
        -r ${genome_tar} \
        -l ${repeats_tar} \
        ${gencode} \
        -n ${default='16' nthreads} \
        -f ${default='5907' f} \
        -y ${default='7' y}
    }

    output {
        File output_variable = ('${sample + "_*" + ".tar.gz"}')
    }

    runtime {
        docker: 'warbler/xtea_germline:v0.2.1'
    }
}
```

**Comment by simoncchu** [comment]
Thank you for sharing! We recently tried on aws with the cwl here: https://github.com/parklab/xTea/blob/master/xtea_germline_hg38.cwl, does this work for you?

**Comment by ohan-Bioinfo** [comment]
I am afraid fire cloud as stated in the readme doesn't support cwl language, so I had to convert the scripts into a wdl with some manipulations, 

and if the script succeded in the cloud i would assume can be found at the workflows but cant be found

**Comment by ohan-Bioinfo** [comment]
The image   dockerPull: warbler/xtea_germline:v0.2.1 can't be pulled would you please check

**Comment by ohan-Bioinfo** [comment]
```
docker pull warbler/xtea_germline:0
Error response from daemon: manifest for warbler/xtea_germline:0 not found: manifest unknown: manifest unknown

```

**Comment by simoncchu** [comment]
Recently, I set up a version here: https://github.com/dbmi-bgm/xTea-germline, could you try this one? The one in the docker file is in my private account.
