### ISSUE TITLE
Can't install on Mac

### ISSUE THREAD

**Issue by proukakis** [parklab/xTea#6]
Hi, trying to install via miniconda3 on Mac with OS Mojave. I though any python greater than 3.6 would do, but it seems not to allow my python (3.8)- or maybe there are other issues which i don't fully understand. I guess i can try to go to 3.6

conda install numpy scikit-learn=0.18.1 pandas -y
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: | 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed                                                                          

UnsatisfiableError: The following specifications were found
to be incompatible with the existing python installation in your environment:

Specifications:

  - scikit-learn=0.18.1 -> python[version='2.7.*|3.5.*|3.6.*']

Your python: python=3.8

If python is on the left-most side of the chain, that's the version you've asked for.
When python appears to the right, that indicates that the thing on the left is somehow
not available for the python version you are constrained to. Note that conda will not
change your python version to a different minor version unless you explicitly specify
that.

The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions

Package libgfortran4 conflicts for:
scikit-learn=0.18.1 -> scipy -> libgfortran4[version='>=7.5.0']
numpy -> libblas[version='>=3.8.0,<4.0a0'] -> libgfortran4[version='>=7.5.0']

Package numpy conflicts for:
pandas -> numpy[version='1.10.*|1.11.*|1.12.*|1.13.*|>=1.11|>=1.11.*|>=1.12.1,<2.0a0|>=1.14.6,<2.0a0|>=1.15.4,<2.0a0|>=1.16.5,<2.0a0|>=1.16.6,<2.0a0|>=1.17.5,<2.0a0|>=1.19.5,<2.0a0|>=1.19.4,<2.0a0|>=1.18.5,<2.0a0|>=1.19.2,<2.0a0|>=1.18.4,<2.0a0|>=1.18.1,<2.0a0|>=1.9.3,<2.0a0|>=1.9.*|>=1.9|>=1.8|>=1.7|>=1.13.3,<2.0a0|>=1.11.3,<2.0a0|>=1.9.3,<1.10.0a0']
scikit-learn=0.18.1 -> scipy -> numpy[version='1.10.*|1.13.*|>=1.11|>=1.11.3,<2.0a0|>=1.14.6,<2.0a0|>=1.16.5,<2.0a0|>=1.16.6,<2.0a0|>=1.17.5,<2.0a0|>=1.19.5,<2.0a0|>=1.19.4,<2.0a0|>=1.18.5,<2.0a0|>=1.19.2,<2.0a0|>=1.18.1,<2.0a0|>=1.9.3,<2.0a0|>=1.9|>=1.15.1,<2.0a0']
scikit-learn=0.18.1 -> numpy[version='1.11.*|1.12.*']

Package libcxxabi conflicts for:
python=3.8 -> libcxx[version='>=4.0.1'] -> libcxxabi[version='4.0.1|4.0.1|8.0.0|8.0.0|8.0.0|8.0.0|8.0.1',build='hebd6815_0|hcfea43d_1|1|3|0|4|2']
pandas -> libcxx[version='>=4.0.1'] -> libcxxabi[version='4.0.1|4.0.1|8.0.0|8.0.0|8.0.0|8.0.0|8.0.1',build='hebd6815_0|hcfea43d_1|1|3|0|4|2']
numpy -> libcxx[version='>=4.0.1'] -> libcxxabi[version='4.0.1|4.0.1|8.0.0|8.0.0|8.0.0|8.0.0|8.0.1',build='hebd6815_0|hcfea43d_1|1|3|0|4|2']

Package mkl_fft conflicts for:
numpy -> mkl_fft[version='>=1.0.14,<2.0a0|>=1.0.4|>=1.0.6,<2.0a0|>=1.2.1,<2.0a0']
pandas -> numpy[version='>=1.19.5,<2.0a0'] -> mkl_fft[version='>=1.0.14,<2.0a0|>=1.0.6,<2.0a0|>=1.2.1,<2.0a0|>=1.0.4']

**Comment by simoncchu** [comment]
@proukakis I think it may not work for MAC. I mainly tested on linux clusters. Also, if you try on python 3.6, does the error repeat?

**Comment by proukakis** [comment]
I haven't tried python 3.6, will do and let you know, thanks

**Comment by proukakis** [comment]
so, in python 3.6, after using
conda create -n your_env xtea=0.1.6
seems OK- i can get it to display help. Will test a proper run later and let you know.

**Comment by simoncchu** [comment]
Thank you for letting me know. One of a colleague reported a softlink error from MAC. Maybe you will meet the same error. But I highly suggest to try on linux.
