### ISSUE TITLE
Stop during  analysis using nanopore data

### ISSUE THREAD

**Issue by kendaida** [parklab/xTea#61]
Hi thank you for developing great tool!

I am a beginner in these analysis.
I am using nanopore data, but the analysis stopped for more than 24 hours during the mapping with having error message many times as below.
I checked all the dependencies are updated.
Would you please give me some advice?

1 contigs 14 edges 23606 bases
** PROC_STAT(TOTAL) **: real 1.304 sec, user 2.830 sec, sys 0.150 sec, maxrss 186456.0 kB, maxvsize 2233948.0 kB
---
--
-- total memory      395724272.0 kB
-- available         341485184.0 kB
-- 72 cores
-- Starting program: wtpoa-cns -i /data/TE_insertion/working/3588/tmp/l_asm_tmp/3500/chr2~87407875_3500_wtdbg2.ctg.lay.gz -fo /data/TE_insertion/working/3588/tmp/l_asm_tmp/3500/chr2~87407875_3500_wtdbg2.ctg.lay.fa -t 16
-- pid                     55942
-- date         Mon Oct 17 17:40:17 2022
--
 -- Error: not a PGZF format at 3 block, in thread_pgz_func -- pgzf.h:369 --
*** Error in `wtpoa-cns': free(): corrupted unsorted chunks: 0x000000000044c940 ***

Thank you in advance.

**Comment by simoncchu** [comment]
Hi, does this file exist? `/data/TE_insertion/working/3588/tmp/l_asm_tmp/3500/chr287407875_3500_wtdbg2.ctg.lay.gz`

**Comment by kendaida** [comment]
Thanks for your reply! Yes, it does.

**Comment by simoncchu** [comment]
Will the error repeat if you run `wtpoa-cns -i /data/TE_insertion/working/3588/tmp/l_asm_tmp/3500/chr287407875_3500_wtdbg2.ctg.lay.gz -fo /data/TE_insertion/working/3588/tmp/l_asm_tmp/3500/chr287407875_3500_wtdbg2.ctg.lay.fa -t 16` ?

**Comment by kendaida** [comment]
It runs like below. Seems to be empty...
--
-- total memory      527910884.0 kB
-- available         480009748.0 kB
-- 128 cores
-- Starting program: wtpoa-cns -i /data/TE_insertion/working/3588/tmp/l_asm_tmp/3500/chr2~87407875_3500_wtdbg2.ctg.lay.gz -fo /data/TE_insertion/working/3588/tmp/l_asm_tmp/3500/chr2~87407875_3500_wtdbg2.ctg.lay.fa -t 16
-- pid                     46338
-- date         Sun Oct 23 14:07:59 2022
--
0 contigs 0 edges 0 bases
** PROC_STAT(TOTAL) **: real 0.405 sec, user 0.010 sec, sys 0.020 sec, maxrss 29016.0 kB, maxvsize 2006960.0 kB
---

**Comment by simoncchu** [comment]
I think it's an error happed earlier before this step that generated empty files. But not sure exactly at which step. Could you try to run with a larger memory?

**Comment by kendaida** [comment]
Thank you for your suggestion!
I'll try again!

2022年10月23日(日) 22:16 Simon C Chu ***@***.***>:
