### ISSUE TITLE
Combine long and short reads?

### ISSUE THREAD

**Issue by aniko-meijer** [parklab/xTea#62]
Hi!

In the Nat. Comm. paper (2021) you mention that:

"For datasets consisting of Illumina short reads and long reads, candidates from Illumina short reads are merged with candidates from long reads, and local assembly is conducted using long reads for each site"

I'm sorry if I missed it, but in the documentation I could not find how to run xTEA in this mode, i. e. obtaining a single output file from two bam files: the PacBio long-read alignment and the illumina short-read alignment. Could you help me with this?

Thank you,
Anikó

**Comment by simoncchu** [comment]
Hi, you need to run xtea on the short reads that generate several outputs. You can use the final vcf (or any intermediate files for higher sensitivity, but longer running time) as the extra input for the long read module. Then, you need to feed in the output from short reads to the long read module. This is not exported in the current release. In the generated `submit_jobs.sh` (or user specific script), there is an assembly step starts like `python l_main.py -A --collect_asm`, you need to add the following option `--i2 extra_source_from_short_reads.txt`, where `extra_source_from_short_reads.txt` is the file generated in the short read part (first two columns must be `chrm` and `position`).
