### ISSUE TITLE
Using xTEa for Drosophila

### ISSUE THREAD

**Issue by adriludwig** [parklab/xTea#63]
Hi! I'd like to test this tool in Drosophila. We are currently using Mobster, but we up to test new ones and I saw your talk in Uppsala. We have a good TE library with consensus and correct classification.  But,I have some simple questions, sorry for that:
- Do we need some specific format for the header of the TE fasta file?
- For the fasta full length sequences, is there a percentage of the total length that I should set? I mean, I'm wondering how this file can impact the result if I don't choose the right size.
- Did you already noticed the use of this tool in other species?
Thank you very much

**Comment by simoncchu** [comment]
Hi, I didn't test on Drosophila, but I think maybe you can follow this thread to have a test: https://github.com/parklab/xTea/issues/20
