### ISSUE TITLE
germline_cloud_v38.py  pysam.utils.SamtoolsError

### ISSUE THREAD

**Issue by ohan-Bioinfo** [parklab/xTea#66]
If i try to use the script 

```
python gnrt_pipeline_germline_cloud_v38.py -i LocalData/Txt/id.txt -b LocalData/Txt/bam.txt --xtea ./ -p ./ -o submit.sh -l LocalData/RepeatLib/ -r LocalData/HumanGenome/GCF_000001405.40_GRCh38.p14_genomic.fna -g LocalData/HumanGenome/GCF_000001405.40_GRCh38.p14_genomic.gff -y 1 -x null -f 5907
Traceback (most recent call last):
  File "gnrt_pipeline_germline_cloud_v38.py", line 776, in <module>
    pysam.index(sf_case_bam)
  File "/miniconda/lib/python3.8/site-packages/pysam/utils.py", line 69, in __call__
    raise SamtoolsError(
pysam.utils.SamtoolsError: 'samtools returned with error 1: stdout=, stderr=samtools index: "LocalData/Txt/bam.txt" is in a format that cannot be usefully indexed\n'
```

but when i replace the script with local script works fine:
`python gnrt_pipeline_local_v38.py -i LocalData/Txt/id.txt -b LocalData/Txt/bam.txt --xtea ./ -p ./ -o submit.sh -l LocalData/RepeatLib/ -r LocalData/HumanGenome/GCF_000001405.40_GRCh38.p14_genomic.fna -g LocalData/HumanGenome/GCF_000001405.40_GRCh38.p14_genomic.gff -y 1 -x null -f 5907`

im still checking scripts and what the suitable one to work in WDL scripts?
Is there any scripts able to take the inputs rather that writing the path and name in a text file?

**Comment by simoncchu** [comment]
right now. no this option.
