### ISSUE TITLE
xTEA long help file -y parameter

### ISSUE THREAD

**Issue by aniko-meijer** [parklab/xTea#67]
Hi Simon,

Thank again for making xTEA and for your quick reply to my previous questions.

When running xTEA long, I noticed a possible mistake in the xtea_long --help output: for the -y parameter you define: 1-LINE1, 2-Alu, 4-SVA, 8-HERV, 16-Mitochondria, but I suspect that 4 should be HERV and 8 SVA?  https://github.com/parklab/xTea/blob/2e18f514ef9c18309852f3c909b8e1fc8c777067/xtea_long/l_rep_classification.py#L306

Thank you,
Kind regards,
Anikó

**Comment by simoncchu** [comment]
Hi Anikó,

The long read one I have a different readme here (4 for HERV and 8 for SVA):
https://github.com/parklab/xTea/tree/xTea_long_release_v0.1.0 

It is not consistent. I'll try to keep the short and long consistent in the next release.
