### ISSUE TITLE
Question about BGISEQ-500 using xtea

### ISSUE THREAD

**Issue by huangyuanf** [parklab/xTea#69]
Dear Professor,

    Nice to meet you!

    I'm sorry to bother you!

    I'm very interested in xtea, the software you developed.I want to use it to identify transposable elements using bgiseq-500 WGS data.But when I run the software, I find the result was not satble.I find the number of Alu varied largely from 400 to 3611, Is this because xtea is not suitable for bgiseq-500 WGS data?

   Thank you! Looking forward to your reply!

**Comment by simoncchu** [comment]
I haven't tried on BGISEQ-500. In theory should work well. What's the depth, read length and insert size of your data?Perhaps need to adjust some parameters.

**Comment by simoncchu** [comment]
Closing for now. If you have further follow-up, please reopen.
