### ISSUE TITLE
Issue with generated run_xTEA_pipeline.sh script 

### ISSUE THREAD

**Issue by slavictoast** [parklab/xTea#71]
Dear all,

I used bwa-mem to align my samples (human WGS) to hg38, transformed sam to bam and bam to sorted bam via samtools.
The generated sorted bam files are used as input in the script generation step of xTea
following command was used in the bash terminal (I used ... to spare you from the whole paths)

$ xtea -i xTea_sampleIDs.txt -b xTea_sampleID_bam.txt -x null -p .../xTea -o submit_jobs.sh -l '.../xTea/rep_lib_annotation'  -r '.../hg38.fa' -g '.../xTea/gencode.v33.annotation.gff3' --xtea '.../xTea/xtea' -f 5907 -y 4 -n 4 -m 15

To use the xTEA_pipeline.sh script for one of the samples I navigated into the generated files containing the script and started it
($ sh '.../SVA/run_xTEA_pipeline.sh' )

Following errors occured:
[E::idx_find_and_load] Could not retrieve index file for (path of sorted bam of the sample) -> several times, some other errors and at the end:
x_TEA_main.py: error: no such option: --bamsnap

Did I perhaps misunderstood what's needed as the input files and have to additionally transform them?
Thank you!

Valentina

**Comment by slavictoast** [comment]
Update: I was able to erase the first error by indexing the sorted bam files 
($ samtools index >sorted bam file<)
But the last error remains:
Usage: x_TEA_main.py [options]

x_TEA_main.py: error: no such option: --bamsnap

**Comment by simoncchu** [comment]
You can ignore this error for now. Same as https://github.com/parklab/xTea/issues/19, I'll resolve this one in the next release.
