### ISSUE TITLE
sklearn version?

### ISSUE THREAD

**Issue by mukamel-lab** [parklab/xTea#76]
I am having trouble running xtea. When trying to load the file:

`xTea/xtea/genotyping/trained_model_ssc_py2_random_forest_two_category.pkl`

I get an error that seems to be related to the version of scikit-learn. It is expecting to have sklearn.ensemble.forest, but I guess this is deprecated. When I downgrade to scikit-learn==0.18.1, I am still unable to load the pickled file using joblib.load(). However, np.load() does work.

However, when I install deep-forest, it requires scikit-learn>=0.22

Any help would be much appreciated!

**Comment by simoncchu** [comment]
Hi, could you try to use the github version (git clone https://github.com/parklab/xTea), rather than the bioconda version, then install deep-forest and try? It will not trigger the error you met.
