### ISSUE TITLE
rep_lib_annotation.tar.gz not a gzip file

### ISSUE THREAD

**Issue by iamTad** [parklab/xTea#8]
Hi,

I've run git clone to retrieve the files from this repository and tried to decompress rep_lib_annotation.tar.gz (I believe it says the path to the decompressed version is required). I tried to unpack it with tar -zvxf and get the following error:

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now

I also notice that cloning the file (on various computers) results in a different much smaller file size than the one shown on github (134 bytes vs 300 MB).

Would it be possible to share this file through other means? Thanks.

**Comment by simoncchu** [comment]
The file is large thus uploaded with git LFS. In the readme, we show clearly to download with `wget https://github.com/parklab/xTea/raw/master/rep_lib_annotation.tar.gz`. Or you can directly click the file to download it.
