### ISSUE TITLE
Handling duplicates

### ISSUE THREAD

**Issue by mikecuoco** [parklab/xTea#80]
Hi @simoncchu thanks for writing this great program. How does xTea handle duplicates? Should users deduplicate our BAMs prior to running xTea?

**Comment by simoncchu** [comment]
Hi @mikecuoco, it will skip the duplicated reads labelled in the "FLAG" field in each alignment, so need to run mark duplication on the bam first, although may not affected that much if this is for germline calling.

**Comment by mikecuoco** [comment]
Great, thanks!
