### ISSUE TITLE
HERV doesn't generate .vcf and gets error while reading reads_fa folder

### ISSUE THREAD

**Issue by eduymaz** [parklab/xTea#82]
Hi! 

I cannot generate .vcf results in my HERV file; you have a comment about this 
https://github.com/parklab/xTea/issues/10#issuecomment-998095493. After the last version, you answered another question about this situation as https://github.com/parklab/xTea/issues/55#issuecomment-1221578041. Do we expect the HERV output still not to produce a .vcf file? If the result file is "candidate_disc_filtered_cns.txt", how can I access the header information of the file? 

In addition; I get an error like below during HERV operations. Is this error directly related to the result file? I would appreciate your valuable comment.
![HERVerror](https://user-images.githubusercontent.com/97849933/236505282-ab554bbd-f655-494c-834e-0aa40f516e07.png)

**Comment by simoncchu** [comment]
Hi, sorry for the late reply. Yes, still no VCF generated for HERV. It's on my list, but just delayed by other works. I'll try to update soon. The first few columns are `chrm`, `representative-breakpoint`, `left-breakpoint`, `right-breakpoint`, `TSD`, `left-supporting-clip-reads`, `right-supporting-clip-reads`, `left-supporting-discordant-reads`, `right-supporting-discordant-reads`, `left-polyA`, `right-polyA`, `left-read-depth`, `right-read-depth`...

This error doesn't affect the final results.
