### ISSUE TITLE
Cannot find the target directory

### ISSUE THREAD

**Issue by zshu-alt** [parklab/xTea#83]
Hello, I have such an error in the process of running, showing RuntimeError: Cannot find the target directory: $HOME/database/xTea/xTea/xtea/genotyping/trained_model_ssc_py2_random_forest_two_category.pkl.  But I'm sure the file exists and is readable and writable. My data is short read data and I hope to conduct Alu analysis. My log files and commands have been uploaded. I would be grateful if you could solve my problem.
[run_xTEA_pipeline.txt](https://github.com/parklab/xTea/files/11654840/run_xTEA_pipeline.txt)
[xTea.txt](https://github.com/parklab/xTea/files/11654841/xTea.txt)
[alu_WGS.txt](https://github.com/parklab/xTea/files/11654842/alu_WGS.txt)

**Comment by hzlnutspread** [comment]
Hi there @simoncchu I also have the exact same problem. There is a trained_model_ssc_py2_random_forest_two_category.pkl file that is generated but it is not a directory and I get the same error when running the pipeline through conda. Would be great to have this issue solved

**Comment by simoncchu** [comment]
Hi, if you use the github version, do you have the same issue?
