### ISSUE TITLE
Pre-generated Alu database

### ISSUE THREAD

**Issue by drtconway** [parklab/xTea#85]
Hi xTea,

Thanks for putting out a tool which produces good results!

Can I ask about the pre-built database? The Alu database has the file name `hg38_AluJabc_copies_with_flank.fa` but looking at the content, it appears that the Alu sequences are `AluY[abc]` sequences.

First, is there a reason for the inconsistent file naming?

Second, can you explain the reason the database contains just the `AluY` sequences and not the other classes of Alu? I assume there are good reasons, but I couldn't see them documented in the paper or the `xTea` documentation.

**Comment by simoncchu** [comment]
Those are AluY abc, as they are the major active ones.
