### ISSUE TITLE
hg38_mitochondrion_copies_with_flank.fa does not exist

### ISSUE THREAD

**Issue by apaul7** [parklab/xTea#9]
Hi,
Thanks for making this tool!

I am running version `0.1.7` installed using conda. 

I am trying to run repeat analysis for Mitochondrial using `-y 16`. The pipeline scripts are generated, I am able to launch the main script, the pipeline runs through part of the analysis. Eventually it runs into an issue and reports an issue with the `L1_COPY_WITH_FLANK` input not existing. This variable is set in the `run_xTEA_pipeline.sh` script. 

The generator scripts [here](https://github.com/parklab/xTea/blob/5cc410b10f7e45a1fda73494bbb7d55c3f948ddf/xtea/gnrt_pipeline_local_v38.py#L687-L690) and [here](https://github.com/parklab/xTea/blob/5cc410b10f7e45a1fda73494bbb7d55c3f948ddf/bin/xtea#L687-L690) report it being located within the rep annotation directory, `${rep_lib_annotation}/Mitochondrion/hg38/hg38_mitochondrion_copies_with_flank.fa`. There is no directory called `Mitochondrion` within the rep_lib_annotation tar ball. Looks like some of the other variables are also set to non existing files, `ANNOTATION` and `ANNOTATION1`. 

Can you point me to where I can download these necessary input files?

Thanks,
-Alex

**Comment by simoncchu** [comment]
Hi Alex, the mitochondrial module is not exported in the current version yet. Mainly because we don't have good benchmark to evaluate the performance. Thus also not included in the paper. I'll try to release a pilot version for test asap.

**Comment by blaverty** [comment]
Hi! I'm wondering if you've made any progress on this?
