### ISSUE TITLE
Questions about the output file

### ISSUE THREAD

**Issue by zshu-alt** [parklab/xTea#90]
Hello, thank you very much for your software, the disease I study is a genetic disease, I want to find the Alu element in the SMN region, the SMN gene region is rich in Alu transposable elements, but the result file shows that no Alu has been detected on the SMN1 gene. Is it the filter condition? I would appreciate it if you could answer my questions.

**Comment by simoncchu** [comment]
Are you looking for germline/de novo pathogenic Alu insertions in the SMN1 gene? It may depends on the sample size I think. You can try with lower cutoff:

```
 The following cutoffs will be automatically set based on read depth (and also purity in the case of a tumor sample); 
 These parameters have been thoroughly tuned based on the use of benchmark data and also on a large cohort analysis. 
 For advanced users (optional major cutoffs):
 	--user: by default, this is turned off. If this option is set, then a user-specific cutoff will be used;
 	--nclip: minimum number of clipped reads;
 	--cr: minimum number of clipped reads whose mates map to repetitive regions;
 	--nd: minimum number of discordant pairs;
```

Also, there are different levels of output under the same folder as the vcf file. You may also check those ones.

**Comment by simoncchu** [comment]
Well, that's not what I could know. How do you know there must be Alu insertions within SMN? Here, I only try to help to resolve technic issues for using xTea, not for research questions.
