### ISSUE TITLE
line 1133, IOError: [Errno 2] No such file or directory: 'null'

### ISSUE THREAD

**Issue by sidi-yang** [parklab/xTea#99]
Dear Simon,

I tried to run xTea with case_control mode using Illumina short read sequencing data (two bam files from one sample, one normal and one tumour) but I got some errors.

Here is my command line:

`xtea -C --tumor -i sample_id.txt -b case_ctrl_bam_list.txt -x null -p /SAN/colcc/sarcoma_bloodcancer/Sidi/xTea/ -o run_xTea_pipeline.sh -l /SAN/colcc/sarcoma_bloodcancer/Sidi/xTea/rep_lib_annotation/ -r /SAN/colcc/sarcoma_bloodcancer/Sidi/GRCh38_latest_genomic.fa -g /SAN/colcc/sarcoma_bloodcancer/Sidi/xTea/gencode.v33.chr_patch_hapl_scaff.annotation.gff3 --xtea /home/sidiyang/xTea/xtea/ -y 1 -f 5907`

And I got error:

`Traceback (most recent call last):
  File "/home/sidiyang/xTea/bin/xtea", line 1329, in <module>
    prepare_case_control_bam(sf_bams, sf_sprt_bams, sf_control_bams)
  File "/home/sidiyang/xTea/bin/xtea", line 1133, in prepare_case_control_bam
    with open(sf_ori_bam) as fin_ori, open(sf_sprt_bam, "w") as fout_sprt, open(sf_control_bam, "w") as fout_ctrl:
IOError: [Errno 2] No such file or directory: 'null'`

In the command line I only set `-x` as `null` because I'm not using 10X sequencing data but I don't know why this error came up.

And I'm also confused about the `-f` option, I see you mention that `5907` stand for all steps, but what are these steps? How do I get this number?

And another thing I want to mention is that after I install the xTea using `git clone https://github.com/parklab/xTea.git`, I noticed that the `-help` option seemed a little different from that in this GitHub readme part.  In the `-help` page, it says that ` -f FLAG, --flag=FLAG  Flag indicates which step to run (1-clip, 2-disc, 4-barcode, 8-xfilter, 16-filter, 32-asm)`, however in the readme file it is `-f: steps to run. (5907 means run all the steps)`.

Just wondering could you please help me with my error and my question about `-f` option?

Thank you very much,
Sidi

**Comment by simoncchu** [comment]
Hi Sidi, could you try with the non-conda version (following the readme page)? The conda version I haven't update for a while, it may trigger some wired error. 

You can try with `-f 1`,  `-f 2` or other options, just for different configurations (e.g. 10X, Illumina), it will combine different steps. Thus I would suggest to try with `-f 5907` and go through the analysis first.
